export const AUDIO_SCRIPTS: Record<number, string> = {
  1: `Hé, welkom. Dit is dag één. En vandaag gaat het over iets heel simpels - maar ook iets wat we bijna allemaal missen. Het moment dat je thuiskomt. Die deur gaat open. Je kind is ergens in huis. Misschien rennen ze naar je toe, misschien niet. En jij? Jij hebt je hoofd nog vol met werk, met verkeer, met alles wat er die dag gebeurd is. Vandaag ga je dat anders doen. Niet met een grote speech. Niet met cadeautjes of overdreven enthousiasme. Gewoon: even stoppen. Ademhalen. En dan pas naar binnen lopen. Echt naar binnen. Met je aandacht erbij. Het klinkt klein. Maar voor je kind voelt het groot. Vandaag, als je thuiskomt - pauzeer even voor die deur. Eén ademhaling. En stap dan naar binnen alsof het de belangrijkste plek is waar je vandaag kunt zijn.`,

  2: `Stel je voor: het is avond. De dag zit erop. Je kind moet naar bed - en eerlijk, jij wilt ook dat het nu gewoon even klaar is. Herkenbaar? Dat slaapmoment, dat is geen obstakel. Dat is een kans. Eentje die je makkelijk mist als je op de automatische piloot staat. Vandaag kijken we naar het slaapkamerritueel. Niet als iets wat je moet afvinken, maar als het rustigste moment van de dag. Het moment waarop je kind het meest open is. Het meest zacht. En jij bepaalt de sfeer. Niet met perfectie, maar met tempo. Langzamer praten. Zachter bewegen. Vanavond doe je een experiment: doe alles rond bedtijd tien procent langzamer dan je gewend bent. Merk op wat dat doet. Met je kind. En met jezelf.`,

  3: `Ik wil je vandaag iets vragen. Denk aan de laatste keer dat je kind zich moeilijk gedroeg. Boos werd, of juist helemaal stil. Wat zag je? En belangrijker - wat zag je niet? Kinderen zijn niet zo goed in woorden als wij. Ze hebben niet altijd de taal voor wat ze voelen. Dus gebruiken ze gedrag. Een driftbui is soms geen driftbui. Het is verdriet. Of angst. Of overweldiging. En als vader is het verleidelijk om te reageren op wat je ziet - het gedrag. Maar vandaag oefenen we met kijken naar wat erachter zit. Niet om het op te lossen. Niet om het weg te praten. Maar om het te herkennen. Vandaag, als je kind iets doet wat je irriteert of verrast - stel jezelf één vraag: wat zou mijn kind nu voelen wat het niet kan zeggen?`,

  4: `Gisteren ging het over zien wat je kind voelt. Vandaag gaan we een stap verder. We gaan het hardop zeggen. Klinkt simpel, toch? Maar het is verrassend moeilijk. Want wij vaders zijn getraind in oplossen. In fixen. Kind huilt? Oplossing zoeken. Kind is boos? Situatie kalmeren. Maar soms is het krachtigste wat je kunt doen gewoon zeggen wat je ziet. "Ik zie dat je boos bent." "Je vindt dit spannend, hè?" "Dat was teleurstellend voor je." Geen advies. Geen maar. Gewoon benoemen. Wat er dan gebeurt, is bijzonder. Je kind voelt zich gezien. En een kind dat zich gezien voelt, kalmeert sneller dan een kind dat een oplossing krijgt. Je oefening voor vandaag: benoem minstens één keer hardop wat je kind voelt. Zonder er iets aan vast te plakken.`,

  5: `Oké. Vandaag wordt het even pittig. Want we gaan het hebben over die momenten waarop je kind volledig ontploft. De meltdown. Het schreeuwen, het huilen, het op de grond liggen in de supermarkt. En alles in jou dat zegt: maak dit stoppen. Nu. Ik snap dat. Echt. Maar hier is het ding - je kind heeft op dat moment geen uitleg nodig. Geen consequenties. Geen afleiding. Je kind heeft jou nodig. Stabiel. Rustig. Aanwezig. Niet perfect, niet onbewogen - maar er. Dat is het moeilijkste wat er is. Blijven staan terwijl alles in je wil vluchten of ingrijpen. Vandaag vraag ik je niet om iets te doen. Ik vraag je om iets te laten. Laat de storm uitrazen. Blijf staan. Adem. En als het voorbij is - dan ben je er nog steeds. Dat is genoeg.`,

  6: `Drie seconden. Zo lang duurt het. Die ruimte tussen het moment dat je kind iets doet wat je triggert - en jouw reactie. Drie seconden. Het voelt als niets. Maar in die drie seconden zit alles. Daar zit het verschil tussen reageren en exploderen. Tussen de vader die je wilt zijn en de vader die je bent als je moe bent en het zat bent. Vandaag gaat het niet over grote veranderingen. Het gaat over die ene pauze. Je voelt het aankomen, toch? Die hitte in je borst, die spanning in je kaken. Dat is je sein. Drie seconden. Adem in. En kies dan. Niet perfect. Niet altijd goed. Maar bewust. Vandaag let je op dat moment. Dat ene moment waarop je voelt dat je wilt reageren. En je geeft jezelf drie seconden. Meer niet.`,

  7: `Hoe kom jij eigenlijk ergens aan? Denk er eens over na. Als je 's ochtends de kamer van je kind binnenloopt. Als je na werk de keuken in stapt. Als je bij school aankomt om ze op te halen. Kom je binnen als een wervelwind? Met haast, met je telefoon nog in je hand, met je gedachten drie stappen vooruit? De manier waarop je ergens aankomt, bepaalt de sfeer voor alles wat erna komt. En het mooie is: je kunt dat veranderen. Niet door meer tijd te hebben - die heb je niet. Maar door een seconde eerder te vertragen. Voor je de kamer binnenloopt. Voor je het gesprek begint. Vandaag oefen je met rustig aankomen. Kies één moment - de ochtend, na werk, het maakt niet uit. En kom daar bewust aan. Voeten op de grond. Schouders laten zakken. En dan pas beginnen.`,

  8: `"Nog één keertje!" Kent je die? Je hebt een grens gesteld. Geen snoep meer. Niet meer op de bank springen. We gaan nu echt naar huis. En dan komen die ogen. Die stem. "Nog één keertje, papa. Alsjeblieft?" En je voelt het wankelen. Want het is toch maar één keertje? Wat maakt het uit? Ik ga je niet vertellen dat je altijd nee moet zeggen. Maar ik wil je wel iets meegeven. Een grens die je stelt en daarna loslaat, is geen grens. Het is een suggestie. En kinderen zijn briljant in het verschil voelen. Ze testen niet om je te pesten. Ze testen omdat ze willen weten: is dit echt? Vandaag kies je één grens. Eentje die je stelt. En je houdt hem vast. Niet hard. Niet boos. Maar helder. "Ik snap dat je het vervelend vindt. En toch is het klaar." Dat is genoeg.`,

  9: `Vandaag krijg je een formule. Drie woorden: kort, warm, helder. Dat is alles wat je nodig hebt voor een goede grens. Kort - geen uitleg van vijf minuten. Kinderen haken af na twee zinnen. Warm - je toon maakt het verschil. Je kunt nee zeggen zonder koud te zijn. Helder - geen misschien, geen we-zien-wel, geen als-je-niet-ophoudt-dan. Gewoon duidelijk. Kijk, wij vaders hebben de neiging om óf te veel uit te leggen óf te kort door de bocht te zijn. Te zacht of te hard. En allebei werkt niet echt. Kort, warm, helder is het midden. Het is: "Nee, we gaan nu niet naar buiten. Ik snap dat je dat wilt. Morgen weer." Klaar. Geen discussie. Geen schuldgevoel. Je oefening: gebruik vandaag één keer deze formule. Kort. Warm. Helder. En merk hoe het voelt.`,

  10: `Zaterdagochtend. Je kent het plaatje. Iedereen is thuis. Niemand heeft een plan. Of juist: iedereen heeft een ander plan. Het ene kind wil naar buiten, het andere hangt aan een scherm, er is discussie over ontbijt, en jij hebt eigenlijk ook nog iets voor jezelf nodig. Dit is het echte leven. Geen nette oefening, geen rustig moment. Gewoon chaos. En dat is precies waar het vandaag over gaat. Want alles wat je de afgelopen dagen geoefend hebt - rustig aankomen, grenzen stellen, emoties benoemen - dat gaat nu door elkaar lopen. En dat is oké. Je hoeft niet alles tegelijk perfect te doen. Kies vanmorgen één moment. Eén situatie waarin je bewust iets anders doet dan je automatische reactie. De rest mag rommelig zijn. Het gaat vandaag niet om controle. Het gaat om bewust kiezen in de chaos. Eén keer is genoeg.`,

  11: `Mag ik eerlijk zijn? Dit is misschien wel de moeilijkste dag tot nu toe. Want vandaag gaat het over loslaten. Je kind probeert iets. Schoenen aantrekken. Een toren bouwen. Iets uitknippen. En het gaat - hoe zeg je dat - niet lekker. En jij ziet het. Je handen jeuken. Je weet precies hoe het moet. Eén kleine beweging en het is opgelost. Maar dat is niet wat je kind nodig heeft. Je kind heeft ruimte nodig om het zelf te doen. Om te klungelen. Om het verkeerd te doen. En het dan opnieuw te proberen. Dat is hoe ze leren. Niet van jouw oplossing, maar van hun eigen proces. Vandaag ga je die jeuk in je handen herkennen. Dat moment dat je wilt overnemen. En in plaats daarvan doe je - niets. Je kijkt. Je wacht. En als ze erom vragen, dan help je. Maar pas dan.`,

  12: `Vandaag gaat het rommelig worden. En dat is precies de bedoeling. Je kind dat zelf boterhammen smeert - en de helft op tafel belandt. Zelf water inschenkt - en morst. Zelf z'n jas aantrekt - met de rits helemaal scheef. Het is verleidelijk om het over te nemen. Sneller. Netter. Minder gedoe. Maar elke keer dat je het overneemt, zeg je onbewust: jij kunt dit niet. En elke keer dat je de rommel laat bestaan, zeg je: ik vertrouw je. Dat is een groot verschil. Ik zeg niet dat je huis een slagveld moet worden. Maar vandaag kies je één ding. Eén ding dat je kind zelf mag doen, ook al wordt het een bende. Laat het kliederen. Laat het rommelig zijn. En kijk naar het gezicht van je kind als het lukt. Die trots - die is van hen. Niet van jou. En dat is precies goed.`,

  13: `Goedemorgen. Misschien was gisteren niet je beste dag. Misschien heb je geschreeuwd. Of iets gezegd wat je niet meende. Misschien lag je vannacht wakker met dat knagend gevoel in je maag. Ik ken dat gevoel. En het eerste wat ik je wil zeggen is dit: het feit dat het je raakt, zegt alles over wat voor vader je bent. Slechte vaders liggen daar niet wakker van. Vandaag gaat het over de ochtend erna. Dat ongemakkelijke moment waarop je je kind weer ziet. En je weet dat er iets rechtgezet moet worden. Niet weggestopt, niet genegeerd - maar erkend. Je hoeft het niet meteen perfect te doen. Maar het begint met er zijn. Met oogcontact. Met een hand op een schouder. En misschien, als het moment er is, met eerlijkheid. Vandaag hoef je alleen maar aanwezig te zijn bij wat er gisteren gebeurd is. Niet wegrennen. Er zijn.`,

  14: `Sorry zeggen. Twee woorden. En toch voelt het soms als de moeilijkste zin die er bestaat. Want sorry zeggen tegen je kind, dat voelt kwetsbaar. Alsof je je gezag verliest. Alsof je toegeeft dat je het niet weet. Maar het tegenovergestelde is waar. Een vader die sorry kan zeggen, is sterker dan een vader die altijd gelijk heeft. Vandaag kijken we naar hoe je dat doet. Echt sorry zeggen. Niet "sorry, maar jij begon" - dat is geen sorry. Niet "sorry dat je je zo voelt" - dat is een verwijt in een jasje. Maar: "Ik was te hard. Dat was niet eerlijk naar jou. Het spijt me." Kort. Eerlijk. Zonder maar. Misschien is er iets recents waarvoor je dit wilt doen. Misschien iets van langer geleden. Je hoeft het niet groots aan te pakken. Zoek een rustig moment. Ga op ooghoogte zitten. En zeg het zoals je het meent.`,

  15: `Er is een moment dat elke vader kent. Je kind probeert iets. Klimt ergens op. Fietst zonder zijwieltjes. Doet iets voor het eerst. En jij ziet het misgaan. In slow motion, bijna. En alles in je wil springen. Opvangen. Beschermen. Voorkomen. Dat is liefde. Maar soms is de grootste liefde - kijken hoe ze vallen. En dan kijken hoe ze opstaan. Want als jij altijd vangt, leert je kind nooit dat het zelf kan opstaan. En als het misgaat? Als er tranen zijn? Dan ben jij er. Niet met "zie je wel" of "had ik toch gezegd." Maar met: "Dat was een flinke val. Hoe gaat het?" Dat is de combinatie van vandaag. Loslaten én er zijn. Ruimte geven én opvangen als het nodig is. Vandaag, let op dat moment. Die impuls om in te grijpen. Geef het een seconde langer. En vertrouw dat je kind meer kan dan je denkt.`,

  16: `Heb je weleens geprobeerd om met je tiener te praten? Echt te praten? Dan weet je hoe dat voelt. Oogcontact vermijden. Korte antwoorden. Die muur die er staat. En hoe harder je probeert erdoorheen te komen, hoe hoger die muur wordt. Vandaag leer je een trucje. Stop met tegenover ze gaan zitten. Ga naast ze zitten. Letterlijk. Op de bank. In de auto. Aan de keukentafel, maar dan naast elkaar. Schouder aan schouder. Zonder oogcontact te forceren. Zonder vragen te stellen. Gewoon er zijn. In dezelfde ruimte. Met dezelfde stilte. Dat voelt raar in het begin. Maar voor je kind - en zeker voor een tiener - is dit veiliger dan een gesprek. Dit is: ik ben hier. Zonder druk. Vandaag zoek je één moment om naast je kind te gaan zitten. Zonder agenda. Zonder vraag. Gewoon naast elkaar.`,

  17: `Wanneer heb je voor het laatst iets samen gedaan met je kind? Niet naar ze gekeken terwijl zij iets deden. Niet iets georganiseerd voor ze. Maar echt samen. Schouder aan schouder. Dezelfde klus. Hetzelfde project. Of gewoon: samen de afwas. Vandaag is een uitdaging. Zoek iets om samen te doen. Het maakt niet uit wat. Een wandeling. Iets koken. De auto wassen. Lego bouwen. Het gaat niet om de activiteit. Het gaat om het naast-elkaar-zijn. Zonder dat het een les is. Zonder dat jij de leiding neemt. Zonder uitleg of instructie. Gewoon twee mensen die iets doen. En wat je zult merken is dit: de echte gesprekken komen vanzelf. Niet als je ze plant, maar als je samen bezig bent. Je handen bezig, je mond ontspannen. Dat is wanneer kinderen praten. Plan vandaag iets in. Klein of groot, maakt niet uit. Samen.`,

  18: `Dit wordt een andere dag. Vandaag kijken we niet naar je kind. Vandaag kijken we naar jou. Ik wil je iets vragen, en neem er even de tijd voor. Hoor je weleens de stem van je eigen vader in die van jou? Als je boos wordt. Als je iets verbiedt. Als je troost - of juist niet. We dragen allemaal iets mee. Patronen die we geleerd hebben zonder dat iemand ze ons uitlegde. Sommige daarvan zijn mooi. Die wil je houden. En sommige... niet. Vandaag gaat niet over oordelen. Niet over je vader, niet over jezelf. Het gaat over herkennen. Over eerlijk kijken naar wat je hebt meegekregen en bewust kiezen wat je doorgeeft. Wat wil je behouden? En wat mag stoppen bij jou? Je hoeft hier niet vandaag een antwoord op te hebben. Maar draag de vraag mee. En merk op wanneer je iets zegt of doet dat niet helemaal van jou voelt.`,

  19: `Het is bijna het einde van de dag. En ik wil je iets aanleren dat je kunt blijven doen, lang nadat dit programma voorbij is. Drie vragen. Elke avond. Voor het slapengaan. Eén: wat ging er goed vandaag als vader? Niet perfect. Niet geweldig. Gewoon: wat ging er goed? Twee: wat had ik anders willen doen? Geen zelfkastijding. Gewoon eerlijk kijken. Drie: waar ben ik dankbaar voor? Over mijn kind, over ons gezin, over vandaag. Drie vragen. Twee minuten. Dat is alles. Je hoeft het niet op te schrijven, hoewel dat mag. Je kunt het in je hoofd doen. Onder de douche. In bed. Het punt is dat je elke dag even stopt en terugkijkt. Niet om jezelf af te rekenen, maar om te groeien. Begin vanavond. Drie vragen. En merk hoe het voelt om bewust stil te staan bij de vader die je vandaag was.`,

  20: `De auto. Dat rare kleine kamertje op wielen waar soms de beste gesprekken plaatsvinden. Geen oogcontact, allebei vooruit kijkend, de wereld die voorbij glijdt. Er is iets aan autorijden dat praten makkelijker maakt. Misschien is het de beweging. Misschien het feit dat je niet naar elkaar hoeft te kijken. Misschien is het gewoon de stilte die er mag zijn zonder dat het ongemakkelijk wordt. Vandaag breng ik twee dingen samen. De verbinding van de afgelopen dagen en het reflecteren. In de auto kun je allebei. Een simpele vraag stellen. Of juist niets zeggen en luisteren naar de muziek die je kind kiest. Of samen terugblikken op de dag. Als je vandaag ergens naartoe rijdt met je kind - of morgen, of dit weekend - doe de radio even uit. Of juist aan, op hun keuze. En laat het gebeuren. Geen agenda. Gewoon samen onderweg zijn.`,

  21: `Dag eenentwintig. En vandaag gooi ik alles op één hoop. Aanwezigheid. Emoties benoemen. Rustig blijven. Grenzen stellen. Loslaten. Herstellen. Verbinden. Reflecteren. Acht vaardigheden. Eén zaterdag. Klinkt overweldigend? Dat is het niet. Want je doet dit al. Elke dag. Het verschil is dat je het nu ziet. Vandaag ga je door een gewone dag heen, maar met je ogen open. Je zult merken dat er tientallen momenten zijn waarin je kunt kiezen. Bewust aankomen. Even pauzeren. Een emotie benoemen. Een grens houden. Je kind iets zelf laten doen. Sorry zeggen als het nodig is. Naast iemand gaan zitten. Het hoeft niet allemaal. Kies er drie. Drie momenten vandaag waarop je bewust de vader bent die je wilt zijn. De rest mag gewoon zijn zoals het is. Drie bewuste momenten. Dat is je dag vandaag.`,

  22: `Hé. Hier zijn we dan. Dag tweeëntwintig. De laatste dag. En ik wil eerlijk tegen je zijn: er is niets magisch aan vandaag. Er is geen diploma. Geen finish. Want vaderschap heeft geen eindstreep. Maar er is wel iets veranderd. Jij bent veranderd. Niet omdat je nu alles perfect doet - dat doet niemand. Maar omdat je tweeëntwintig dagen lang hebt gekozen om bewust te kijken. Naar je kind. Naar jezelf. Naar de ruimte daartussen. En dat is zeldzaam. Dat is moedig. Morgenochtend word je wakker en is er geen nieuwe dag van dit programma. Maar er is wel een nieuwe dag met je kind. En je hebt nu iets wat je drie weken geleden niet had: de vaardigheid om te pauzeren. Om te kiezen. Om er te zijn. Dus morgenochtend, als je opstaat - doe het bewust. Loop naar je kind. Kijk ze aan. En weet: dit is waar het om gaat. Niet gisteren. Niet volgende week. Dit moment. Dank je wel dat je er was. Elke dag. Ga zo door.`,
};
