import type { Template } from './instagram-captions';

export interface SocialContent {
  id: string;
  type: 'tip' | 'stat' | 'didyouknow' | 'challenge' | 'comparison' | 'quote' | 'cta';
  skill: string;
  text: string;
  subtitle?: string;
  template: Template;
  /** Pre-filled caption (overrides auto-generated caption when selecting from library) */
  caption?: string;
}

export const SOCIAL_CONTENT: SocialContent[] = [
  // ════════════════════════════════════════════════════════════════════
  // TIPS - Aanwezigheid (10)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'tip-aanw-1',
    type: 'tip',
    skill: 'Aanwezigheid',
    text: 'Leg je telefoon weg als je kind binnenkomt. Die eerste 3 minuten zetten de toon.',
    template: 'tip',
  },
  {
    id: 'tip-aanw-2',
    type: 'tip',
    skill: 'Aanwezigheid',
    text: 'Ga op ooghoogte van je kind zitten. Het verschil in aandacht is direct voelbaar.',
    template: 'tip',
  },
  {
    id: 'tip-aanw-3',
    type: 'tip',
    skill: 'Aanwezigheid',
    text: 'Stel open vragen in plaats van ja/nee-vragen. "Wat was het leukste vandaag?" werkt beter dan "Was het leuk?"',
    template: 'tip',
  },
  {
    id: 'tip-aanw-4',
    type: 'tip',
    skill: 'Aanwezigheid',
    text: 'Plan geen activiteit, maar wees beschikbaar. Kinderen openen zich als er geen agenda is.',
    template: 'tip',
  },
  {
    id: 'tip-aanw-5',
    type: 'tip',
    skill: 'Aanwezigheid',
    text: 'Herhaal wat je kind zegt in je eigen woorden. Zo voelt het zich echt gehoord.',
    template: 'tip',
  },
  {
    id: 'tip-aanw-6',
    type: 'tip',
    skill: 'Aanwezigheid',
    text: 'Kijk je kind aan als het tegen je praat, ook als je moe bent. Oogcontact zegt: jij bent belangrijk.',
    template: 'tip',
  },
  {
    id: 'tip-aanw-7',
    type: 'tip',
    skill: 'Aanwezigheid',
    text: 'Maak van het naar bed brengen een ritueel. Vijf rustige minuten aan het eind van de dag doen wonderen.',
    template: 'tip',
  },
  {
    id: 'tip-aanw-8',
    type: 'tip',
    skill: 'Aanwezigheid',
    text: 'Doe mee met het spel van je kind, zonder het over te nemen. Volg hun regels, niet de jouwe.',
    template: 'tip',
  },
  {
    id: 'tip-aanw-9',
    type: 'tip',
    skill: 'Aanwezigheid',
    text: 'Leg werkgesprekken pas voort nadat je kind klaar is met praten. Het leert dat het prioriteit heeft.',
    template: 'tip',
  },
  {
    id: 'tip-aanw-10',
    type: 'tip',
    skill: 'Aanwezigheid',
    text: 'Twee minuten volledige aandacht is meer waard dan een uur halfslachtig aanwezig zijn.',
    template: 'tip',
  },

  // ════════════════════════════════════════════════════════════════════
  // TIPS - Emotiecoaching (10)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'tip-emot-1',
    type: 'tip',
    skill: 'Emotiecoaching',
    text: 'Benoem de emotie voor je een oplossing biedt: "Ik zie dat je boos bent." Dat alleen al helpt.',
    template: 'tip',
  },
  {
    id: 'tip-emot-2',
    type: 'tip',
    skill: 'Emotiecoaching',
    text: 'Zeg nooit "Stel je niet aan." Daarmee leer je je kind dat zijn gevoelens niet tellen.',
    template: 'tip',
  },
  {
    id: 'tip-emot-3',
    type: 'tip',
    skill: 'Emotiecoaching',
    text: 'Vraag "Hoe voelt dat?" in plaats van "Waarom doe je zo?" Het eerste opent een gesprek, het tweede sluit het.',
    template: 'tip',
  },
  {
    id: 'tip-emot-4',
    type: 'tip',
    skill: 'Emotiecoaching',
    text: 'Laat je kind uithuilen zonder het te sussen. Soms is "Ik ben hier" het enige wat nodig is.',
    template: 'tip',
  },
  {
    id: 'tip-emot-5',
    type: 'tip',
    skill: 'Emotiecoaching',
    text: 'Gebruik zelf emotiewoorden in het dagelijks leven. "Ik voel me gefrustreerd" leert je kind dat emoties normaal zijn.',
    template: 'tip',
  },
  {
    id: 'tip-emot-6',
    type: 'tip',
    skill: 'Emotiecoaching',
    text: 'Na een driftbui: wacht tot de storm voorbij is en bespreek het dan pas. Midden in de storm luistert niemand.',
    template: 'tip',
  },
  {
    id: 'tip-emot-7',
    type: 'tip',
    skill: 'Emotiecoaching',
    text: 'Vertel je kind dat alle gevoelens oké zijn, maar niet al het gedrag. Boos zijn mag - slaan niet.',
    template: 'tip',
  },
  {
    id: 'tip-emot-8',
    type: 'tip',
    skill: 'Emotiecoaching',
    text: 'Maak een "gevoelensthermometer" met je kind. Het helpt bij het leren herkennen van de intensiteit van emoties.',
    template: 'tip',
  },
  {
    id: 'tip-emot-9',
    type: 'tip',
    skill: 'Emotiecoaching',
    text: 'Vermijd "Je hoeft niet bang te zijn." Zeg liever "Ik snap dat dit eng voelt. Ik ben bij je."',
    template: 'tip',
  },
  {
    id: 'tip-emot-10',
    type: 'tip',
    skill: 'Emotiecoaching',
    text: 'Lees samen een boek en vraag hoe de hoofdpersoon zich voelt. Het oefent empathie op een veilige manier.',
    template: 'tip',
  },

  // ════════════════════════════════════════════════════════════════════
  // TIPS - Zelfregulatie (10)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'tip-zelf-1',
    type: 'tip',
    skill: 'Zelfregulatie',
    text: 'Voel je dat je gaat ontploffen? Adem 4 tellen in, 7 tellen vasthouden, 8 tellen uit. Herhaal 3 keer.',
    template: 'tip',
  },
  {
    id: 'tip-zelf-2',
    type: 'tip',
    skill: 'Zelfregulatie',
    text: 'Je hoeft niet meteen te reageren. "Ik moet hier even over nadenken" is een volwassen antwoord.',
    template: 'tip',
  },
  {
    id: 'tip-zelf-3',
    type: 'tip',
    skill: 'Zelfregulatie',
    text: 'Ken je triggers. Honger, slaapgebrek of werkstress maken je reacties groter dan de situatie vraagt.',
    template: 'tip',
  },
  {
    id: 'tip-zelf-4',
    type: 'tip',
    skill: 'Zelfregulatie',
    text: 'Loop even de kamer uit als je merkt dat je stem luider wordt. Dat is geen weglopen, dat is verantwoordelijkheid nemen.',
    template: 'tip',
  },
  {
    id: 'tip-zelf-5',
    type: 'tip',
    skill: 'Zelfregulatie',
    text: 'Slaap is je belangrijkste opvoedtool. Een uitgeruste vader reageert anders dan een uitgeputte.',
    template: 'tip',
  },
  {
    id: 'tip-zelf-6',
    type: 'tip',
    skill: 'Zelfregulatie',
    text: 'Vraag jezelf af: reageer ik nu op mijn kind, of op mijn eigen frustratie? Dat onderscheid maakt alles uit.',
    template: 'tip',
  },
  {
    id: 'tip-zelf-7',
    type: 'tip',
    skill: 'Zelfregulatie',
    text: 'Maak een afspraak met je partner: als een van jullie een teken geeft, neemt de ander het over. Geen schaamte.',
    template: 'tip',
  },
  {
    id: 'tip-zelf-8',
    type: 'tip',
    skill: 'Zelfregulatie',
    text: 'Voel waar de spanning zit in je lichaam. Schouders? Kaak? Vuisten? Bewust ontspannen helpt je brein om te schakelen.',
    template: 'tip',
  },
  {
    id: 'tip-zelf-9',
    type: 'tip',
    skill: 'Zelfregulatie',
    text: 'Je kind kopieert niet je woorden, maar je gedrag. Als jij kalm blijft onder druk, leert je kind dat ook.',
    template: 'tip',
  },
  {
    id: 'tip-zelf-10',
    type: 'tip',
    skill: 'Zelfregulatie',
    text: 'Plan tijd voor jezelf in, zonder schuldgevoel. Je kunt niet geven vanuit een lege tank.',
    template: 'tip',
  },

  // ════════════════════════════════════════════════════════════════════
  // TIPS - Grenzen (10)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'tip-gren-1',
    type: 'tip',
    skill: 'Grenzen',
    text: 'Stel grenzen vooraf, niet als reactie. "Na het eten mag je een half uur schermtijd" werkt beter dan achteraf beperken.',
    template: 'tip',
  },
  {
    id: 'tip-gren-2',
    type: 'tip',
    skill: 'Grenzen',
    text: 'Wees consequent, ook als het makkelijker is om toe te geven. Inconsistentie leert je kind dat zeuren werkt.',
    template: 'tip',
  },
  {
    id: 'tip-gren-3',
    type: 'tip',
    skill: 'Grenzen',
    text: 'Leg uit waarom een grens er is, zonder je te verdedigen. "De regel is..." is genoeg.',
    template: 'tip',
  },
  {
    id: 'tip-gren-4',
    type: 'tip',
    skill: 'Grenzen',
    text: 'Geef twee keuzes in plaats van een verbod. "Wil je nu opruimen of na het eten?" geeft autonomie binnen een grens.',
    template: 'tip',
  },
  {
    id: 'tip-gren-5',
    type: 'tip',
    skill: 'Grenzen',
    text: 'Je kind mag boos zijn op de grens. Dat hoort erbij. Erken de emotie, houd de grens vast.',
    template: 'tip',
  },
  {
    id: 'tip-gren-6',
    type: 'tip',
    skill: 'Grenzen',
    text: 'Spreek als ouders dezelfde grenzen af. Verschillende regels bij papa en mama geeft verwarring.',
    template: 'tip',
  },
  {
    id: 'tip-gren-7',
    type: 'tip',
    skill: 'Grenzen',
    text: 'Minder regels, maar die je hebt echt handhaven. Drie duidelijke grenzen werken beter dan twintig vage.',
    template: 'tip',
  },
  {
    id: 'tip-gren-8',
    type: 'tip',
    skill: 'Grenzen',
    text: 'Zeg wat je kind wel mag, niet alleen wat niet mag. "Loop" in plaats van "Niet rennen!"',
    template: 'tip',
  },
  {
    id: 'tip-gren-9',
    type: 'tip',
    skill: 'Grenzen',
    text: 'Gebruik natuurlijke consequenties waar mogelijk. Speelgoed niet opruimen? Dan is het de volgende dag niet beschikbaar.',
    template: 'tip',
  },
  {
    id: 'tip-gren-10',
    type: 'tip',
    skill: 'Grenzen',
    text: 'Een "nee" hoeft niet hard te zijn. Je kunt vriendelijk en duidelijk tegelijk zijn.',
    template: 'tip',
  },

  // ════════════════════════════════════════════════════════════════════
  // TIPS - Autonomie (10)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'tip-auto-1',
    type: 'tip',
    skill: 'Autonomie',
    text: 'Laat je kind zijn eigen boterham smeren, ook als het langer duurt en rommeliger is. Het leert meer dan jij denkt.',
    template: 'tip',
  },
  {
    id: 'tip-auto-2',
    type: 'tip',
    skill: 'Autonomie',
    text: 'Vervang "Laat mij maar" door "Probeer het eerst zelf, ik help als je vastloopt."',
    template: 'tip',
  },
  {
    id: 'tip-auto-3',
    type: 'tip',
    skill: 'Autonomie',
    text: 'Geef je kind leeftijdsgebonden taken in het huishouden. Verantwoordelijkheid begint klein.',
    template: 'tip',
  },
  {
    id: 'tip-auto-4',
    type: 'tip',
    skill: 'Autonomie',
    text: 'Stel de vraag "Wat denk jij?" voordat je zelf een antwoord geeft. Je zult verrast zijn.',
    template: 'tip',
  },
  {
    id: 'tip-auto-5',
    type: 'tip',
    skill: 'Autonomie',
    text: 'Falen hoort bij leren. Laat je kind de natuurlijke gevolgen ervaren van kleine fouten.',
    template: 'tip',
  },
  {
    id: 'tip-auto-6',
    type: 'tip',
    skill: 'Autonomie',
    text: 'Complimenteer de inspanning, niet het resultaat. "Je hebt hard gewerkt" motiveert meer dan "Wat knap!"',
    template: 'tip',
  },
  {
    id: 'tip-auto-7',
    type: 'tip',
    skill: 'Autonomie',
    text: 'Laat je kind zijn eigen conflicten proberen op te lossen voor je ingrijpt. Coach vanaf de zijlijn.',
    template: 'tip',
  },
  {
    id: 'tip-auto-8',
    type: 'tip',
    skill: 'Autonomie',
    text: 'Geef je kind keuzes die bij zijn leeftijd passen. Een kleuter kiest tussen twee outfits, een tiener plant zijn eigen week.',
    template: 'tip',
  },
  {
    id: 'tip-auto-9',
    type: 'tip',
    skill: 'Autonomie',
    text: 'Weersta de drang om huiswerk over te nemen. Een zelf behaalde 6 is waardevoller dan een papa-gestuurde 8.',
    template: 'tip',
  },
  {
    id: 'tip-auto-10',
    type: 'tip',
    skill: 'Autonomie',
    text: 'Zeg vaker "Ik vertrouw erop dat jij dit kunt." Die woorden bouwen zelfvertrouwen van binnenuit.',
    template: 'tip',
  },

  // ════════════════════════════════════════════════════════════════════
  // TIPS - Herstel (10)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'tip-hers-1',
    type: 'tip',
    skill: 'Herstel',
    text: 'Sorry zeggen naar je kind is geen zwakte. Het is het sterkste wat een vader kan doen.',
    template: 'tip',
  },
  {
    id: 'tip-hers-2',
    type: 'tip',
    skill: 'Herstel',
    text: 'Een goed excuus heeft drie delen: wat je deed, hoe het voor je kind was, en wat je anders gaat doen.',
    template: 'tip',
  },
  {
    id: 'tip-hers-3',
    type: 'tip',
    skill: 'Herstel',
    text: 'Herstel zo snel mogelijk. Hoe langer je wacht, hoe groter het verhaal in het hoofd van je kind wordt.',
    template: 'tip',
  },
  {
    id: 'tip-hers-4',
    type: 'tip',
    skill: 'Herstel',
    text: 'Zeg niet "Sorry, maar jij deed ook..." Een excuus met een maar is geen excuus.',
    template: 'tip',
  },
  {
    id: 'tip-hers-5',
    type: 'tip',
    skill: 'Herstel',
    text: 'Na een uitbarsting: ga terug, ga op ooghoogte zitten, en zeg eerlijk wat er gebeurde. Je kind begrijpt meer dan je denkt.',
    template: 'tip',
  },
  {
    id: 'tip-hers-6',
    type: 'tip',
    skill: 'Herstel',
    text: 'Vraag je kind hoe het zich voelde toen jij boos werd. Luister zonder je te verdedigen.',
    template: 'tip',
  },
  {
    id: 'tip-hers-7',
    type: 'tip',
    skill: 'Herstel',
    text: 'Herstel leert je kind dat relaties tegen een stootje kunnen. Dat is een levensles.',
    template: 'tip',
  },
  {
    id: 'tip-hers-8',
    type: 'tip',
    skill: 'Herstel',
    text: 'Dwing je kind niet om jouw excuus te accepteren. Geef het de tijd om te verwerken.',
    template: 'tip',
  },
  {
    id: 'tip-hers-9',
    type: 'tip',
    skill: 'Herstel',
    text: 'Deel met je kind dat jij ook nog aan het leren bent. Dat maakt je menselijk, niet zwak.',
    template: 'tip',
  },
  {
    id: 'tip-hers-10',
    type: 'tip',
    skill: 'Herstel',
    text: 'Het gaat niet om het voorkomen van alle fouten. Het gaat om wat je doet nadat het misging.',
    template: 'tip',
  },

  // ════════════════════════════════════════════════════════════════════
  // TIPS - Verbinding (10)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'tip-verb-1',
    type: 'tip',
    skill: 'Verbinding',
    text: 'Zoek een activiteit die alleen van jullie twee is. Een eigen ritueel versterkt de band.',
    template: 'tip',
  },
  {
    id: 'tip-verb-2',
    type: 'tip',
    skill: 'Verbinding',
    text: 'Tieners praten niet op commando. De beste gesprekken ontstaan naast elkaar: in de auto, tijdens een wandeling, bij het koken.',
    template: 'tip',
  },
  {
    id: 'tip-verb-3',
    type: 'tip',
    skill: 'Verbinding',
    text: 'Stuur je tiener af en toe een berichtje overdag. Niet om te controleren, maar om te laten weten dat je aan hem denkt.',
    template: 'tip',
  },
  {
    id: 'tip-verb-4',
    type: 'tip',
    skill: 'Verbinding',
    text: 'Toon interesse in wat je kind bezighoudt, ook als je het zelf niet begrijpt. Het gaat niet om het onderwerp, maar om de aandacht.',
    template: 'tip',
  },
  {
    id: 'tip-verb-5',
    type: 'tip',
    skill: 'Verbinding',
    text: 'Lach samen. Humor is een van de snelste manieren om verbinding te herstellen.',
    template: 'tip',
  },
  {
    id: 'tip-verb-6',
    type: 'tip',
    skill: 'Verbinding',
    text: 'Vertel je kind verhalen over toen jij jong was. Het maakt je menselijk en schept herkenning.',
    template: 'tip',
  },
  {
    id: 'tip-verb-7',
    type: 'tip',
    skill: 'Verbinding',
    text: 'Geef af en toe een onverwachte knuffel of schouderklop. Fysiek contact zegt meer dan woorden.',
    template: 'tip',
  },
  {
    id: 'tip-verb-8',
    type: 'tip',
    skill: 'Verbinding',
    text: 'Plan een vaste papa-kind-dag per maand. Het hoeft niets bijzonders te zijn, als het maar van jullie is.',
    template: 'tip',
  },
  {
    id: 'tip-verb-9',
    type: 'tip',
    skill: 'Verbinding',
    text: 'Vraag je puber om hulp bij iets waar hij goed in is. Niets verbindt zo sterk als oprecht om hulp vragen.',
    template: 'tip',
  },
  {
    id: 'tip-verb-10',
    type: 'tip',
    skill: 'Verbinding',
    text: 'Onthoud de kleine dingen die je kind vertelt en kom er later op terug. Dat zegt: ik luister echt.',
    template: 'tip',
  },

  // ════════════════════════════════════════════════════════════════════
  // TIPS - Reflectie (10)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'tip-refl-1',
    type: 'tip',
    skill: 'Reflectie',
    text: 'Stel jezelf elke avond een vraag: wat voor vader was ik vandaag? Niet om te oordelen, maar om te leren.',
    template: 'tip',
  },
  {
    id: 'tip-refl-2',
    type: 'tip',
    skill: 'Reflectie',
    text: 'Merk je dat je reageert zoals je eigen vader deed? Dat is geen falen, dat is bewustwording. En dat is de eerste stap.',
    template: 'tip',
  },
  {
    id: 'tip-refl-3',
    type: 'tip',
    skill: 'Reflectie',
    text: 'Schrijf een keer per week drie dingen op die goed gingen als vader. Reflectie is niet alleen kijken naar wat beter kan.',
    template: 'tip',
  },
  {
    id: 'tip-refl-4',
    type: 'tip',
    skill: 'Reflectie',
    text: 'Vraag je partner eerlijk hoe je overkomt als vader. Luister zonder je te verdedigen.',
    template: 'tip',
  },
  {
    id: 'tip-refl-5',
    type: 'tip',
    skill: 'Reflectie',
    text: 'Welk patroon uit je eigen opvoeding wil je doorbreken? Benoem het concreet. Bewustzijn is de eerste stap naar verandering.',
    template: 'tip',
  },
  {
    id: 'tip-refl-6',
    type: 'tip',
    skill: 'Reflectie',
    text: 'Praat met andere vaders over het vaderschap. Niet over voetbal of werk, maar over hoe het echt gaat.',
    template: 'tip',
  },
  {
    id: 'tip-refl-7',
    type: 'tip',
    skill: 'Reflectie',
    text: 'Je hoeft niet alles te weten. "Ik weet het niet, maar ik zoek het uit" is een krachtig voorbeeld voor je kind.',
    template: 'tip',
  },
  {
    id: 'tip-refl-8',
    type: 'tip',
    skill: 'Reflectie',
    text: 'Merk op wanneer je streng bent uit angst, niet uit overtuiging. Angstgedreven opvoeding voelt anders dan bewuste opvoeding.',
    template: 'tip',
  },
  {
    id: 'tip-refl-9',
    type: 'tip',
    skill: 'Reflectie',
    text: 'De vader die je wilt zijn en de vader die je bent - dat verschil is geen probleem, maar een uitnodiging om te groeien.',
    template: 'tip',
  },
  {
    id: 'tip-refl-10',
    type: 'tip',
    skill: 'Reflectie',
    text: 'Lees een boek over opvoeding per kwartaal. Niet om alles toe te passen, maar om nieuwe perspectieven te vinden.',
    template: 'tip',
  },

  // ════════════════════════════════════════════════════════════════════
  // STATISTICS (32)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'stat-1',
    type: 'stat',
    skill: 'Aanwezigheid',
    text: 'Kinderen met betrokken vaders scoren gemiddeld 43% hoger op schooltoetsen.',
    subtitle: 'National Center for Education Statistics',
    template: 'stat',
  },
  {
    id: 'stat-2',
    type: 'stat',
    skill: 'Emotiecoaching',
    text: 'Kinderen die leren emoties te benoemen hebben 40% minder gedragsproblemen op school.',
    subtitle: 'Yale Center for Emotional Intelligence',
    template: 'stat',
  },
  {
    id: 'stat-3',
    type: 'stat',
    skill: 'Zelfregulatie',
    text: 'Ouders die bewust pauzeren voor ze reageren, schreeuwen 67% minder tegen hun kinderen.',
    subtitle: 'American Psychological Association',
    template: 'stat',
  },
  {
    id: 'stat-4',
    type: 'stat',
    skill: 'Verbinding',
    text: 'Tieners die een goede band hebben met hun vader lopen 80% minder risico op depressie.',
    subtitle: 'Journal of Family Psychology',
    template: 'stat',
  },
  {
    id: 'stat-5',
    type: 'stat',
    skill: 'Grenzen',
    text: 'Kinderen met duidelijke en consequente grenzen voelen zich 3x zo veilig als kinderen zonder.',
    subtitle: 'Universiteit Utrecht, 2019',
    template: 'stat',
  },
  {
    id: 'stat-6',
    type: 'stat',
    skill: 'Herstel',
    text: 'Het is niet de ruzie die de relatie schaadt, maar het ontbreken van herstel erna.',
    subtitle: 'John Gottman Institute',
    template: 'stat',
  },
  {
    id: 'stat-7',
    type: 'stat',
    skill: 'Autonomie',
    text: 'Kinderen die leeftijdsgebonden verantwoordelijkheden krijgen, ontwikkelen 25% meer zelfredzaamheid.',
    subtitle: 'Harvard Grant Study',
    template: 'stat',
  },
  {
    id: 'stat-8',
    type: 'stat',
    skill: 'Reflectie',
    text: 'Vaders die reflecteren op hun opvoeding herhalen 50% minder negatieve patronen uit hun eigen jeugd.',
    subtitle: 'Attachment Research',
    template: 'stat',
  },
  {
    id: 'stat-9',
    type: 'stat',
    skill: 'Aanwezigheid',
    text: 'Nederlandse vaders besteden gemiddeld 45 minuten per dag aan actieve interactie met hun kinderen.',
    subtitle: 'CBS Tijdbestedingsonderzoek',
    template: 'stat',
  },
  {
    id: 'stat-10',
    type: 'stat',
    skill: 'Emotiecoaching',
    text: 'Kinderen van emotioneel beschikbare vaders hebben op 18-jarige leeftijd betere vriendschappen.',
    subtitle: 'Developmental Psychology, 2018',
    template: 'stat',
  },
  {
    id: 'stat-11',
    type: 'stat',
    skill: 'Verbinding',
    text: '1 op de 3 Nederlandse vaders vindt het lastig om over gevoelens te praten met zijn kinderen.',
    subtitle: 'Onderzoek Rutgers, 2021',
    template: 'stat',
  },
  {
    id: 'stat-12',
    type: 'stat',
    skill: 'Zelfregulatie',
    text: 'Kinderen nemen het stressgedrag van hun ouders over. Jouw kalmte is letterlijk besmettelijk.',
    subtitle: 'Social Learning Theory, Bandura',
    template: 'stat',
  },
  {
    id: 'stat-13',
    type: 'stat',
    skill: 'Grenzen',
    text: 'Kinderen testen grenzen gemiddeld 7 keer voor ze accepteren dat een grens echt staat.',
    subtitle: 'Child Development Research',
    template: 'stat',
  },
  {
    id: 'stat-14',
    type: 'stat',
    skill: 'Aanwezigheid',
    text: 'De gemiddelde ouder kijkt 96 keer per dag op zijn telefoon. Kinderen merken dat.',
    subtitle: 'Onderzoek Universiteit van Michigan',
    template: 'stat',
  },
  {
    id: 'stat-15',
    type: 'stat',
    skill: 'Autonomie',
    text: 'Jongeren die als kind zelfstandigheid kregen, hebben als volwassene 30% meer zelfvertrouwen.',
    subtitle: 'Journal of Adolescent Research',
    template: 'stat',
  },
  {
    id: 'stat-16',
    type: 'stat',
    skill: 'Herstel',
    text: 'Kinderen die zien dat hun ouders fouten toegeven, leren sneller eigen fouten te erkennen.',
    subtitle: 'Parenting Science, 2020',
    template: 'stat',
  },
  {
    id: 'stat-17',
    type: 'stat',
    skill: 'Verbinding',
    text: 'Gezinnen die minstens 4 keer per week samen eten, hebben tieners met 35% minder risicogedrag.',
    subtitle: 'National Center on Addiction',
    template: 'stat',
  },
  {
    id: 'stat-18',
    type: 'stat',
    skill: 'Emotiecoaching',
    text: 'Het duurt gemiddeld 20 minuten voordat een kind na een woedeaanval weer kan nadenken. Geduld loont.',
    subtitle: 'Neurobiologisch onderzoek, 2019',
    template: 'stat',
  },
  {
    id: 'stat-19',
    type: 'stat',
    skill: 'Reflectie',
    text: '72% van de vaders zegt dat ze bewuster opvoeden dan hun eigen ouders deden.',
    subtitle: 'Nationaal Ouderonderzoek, 2022',
    template: 'stat',
  },
  {
    id: 'stat-20',
    type: 'stat',
    skill: 'Zelfregulatie',
    text: 'Na 6 seconden bewust ademhalen daalt je stressniveau merkbaar. Dat is alles wat je nodig hebt.',
    subtitle: 'HeartMath Institute',
    template: 'stat',
  },
  {
    id: 'stat-21',
    type: 'stat',
    skill: 'Aanwezigheid',
    text: 'Kinderen die dagelijks 15 minuten onverdeelde aandacht krijgen, vertonen 50% minder aandachtvragend gedrag.',
    subtitle: 'Journal of Child Psychology',
    template: 'stat',
  },
  {
    id: 'stat-22',
    type: 'stat',
    skill: 'Grenzen',
    text: 'Autoritatief opvoeden - warm en duidelijk tegelijk - leidt tot de beste resultaten op alle fronten.',
    subtitle: 'Diana Baumrind, opvoedingsonderzoek',
    template: 'stat',
  },
  {
    id: 'stat-23',
    type: 'stat',
    skill: 'Verbinding',
    text: 'Vaders die spelen met hun kinderen versterken de band sterker dan vaders die alleen verzorgen.',
    subtitle: 'Fatherhood Institute, UK',
    template: 'stat',
  },
  {
    id: 'stat-24',
    type: 'stat',
    skill: 'Autonomie',
    text: 'De gemiddelde leeftijd waarop kinderen hun eerste eigen verantwoordelijkheid krijgen is gedaald naar 8 jaar. Eerder kan prima.',
    subtitle: 'Opvoedingsonderzoek NL',
    template: 'stat',
  },
  {
    id: 'stat-25',
    type: 'stat',
    skill: 'Herstel',
    text: 'Vaders die sorry zeggen worden door hun kinderen niet als zwak gezien, maar juist als sterker.',
    subtitle: 'Onderzoek University of Waterloo',
    template: 'stat',
  },
  {
    id: 'stat-26',
    type: 'stat',
    skill: 'Emotiecoaching',
    text: 'Jongens die leren dat huilen mag, hebben als volwassene 45% minder kans op depressie.',
    subtitle: 'Mental Health Foundation',
    template: 'stat',
  },
  {
    id: 'stat-27',
    type: 'stat',
    skill: 'Reflectie',
    text: '5 minuten dagelijkse reflectie over je vaderschap heeft meer effect dan een uur per maand.',
    subtitle: 'Mindfulness Research',
    template: 'stat',
  },
  {
    id: 'stat-28',
    type: 'stat',
    skill: 'Zelfregulatie',
    text: 'Ouders die hun eigen emoties benoemen, hebben kinderen die dat ook 2x vaker doen.',
    subtitle: 'Emotion Socialization Research',
    template: 'stat',
  },
  {
    id: 'stat-29',
    type: 'stat',
    skill: 'Aanwezigheid',
    text: '87% van de volwassenen herinnert zich niet wat hun ouders zeiden, maar wel hoe ze zich voelden in hun aanwezigheid.',
    subtitle: 'Geheugenonderzoek, 2017',
    template: 'stat',
  },
  {
    id: 'stat-30',
    type: 'stat',
    skill: 'Grenzen',
    text: 'Kinderen voelen zich veiliger bij een vader die "nee" zegt dan bij een vader die alles goedvindt.',
    subtitle: 'Attachment Theory Research',
    template: 'stat',
  },
  {
    id: 'stat-31',
    type: 'stat',
    skill: 'Verbinding',
    text: 'De kwaliteit van de vader-kindrelatie op 7-jarige leeftijd voorspelt het welzijn op 33-jarige leeftijd.',
    subtitle: 'British Cohort Study',
    template: 'stat',
  },
  {
    id: 'stat-32',
    type: 'stat',
    skill: 'Autonomie',
    text: 'Helikopterouders bedoelen het goed, maar hun kinderen ervaren 60% meer angst bij nieuwe situaties.',
    subtitle: 'Journal of Child and Family Studies',
    template: 'stat',
  },

  // ════════════════════════════════════════════════════════════════════
  // WIST JE DAT / DID YOU KNOW (28)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'dyk-1',
    type: 'didyouknow',
    skill: 'Emotiecoaching',
    text: 'kinderen die hun emoties mogen uiten 2x sneller leren ze te reguleren?',
    template: 'didyouknow',
  },
  {
    id: 'dyk-2',
    type: 'didyouknow',
    skill: 'Aanwezigheid',
    text: 'je kind binnen 8 seconden beslist of je echt luistert of alleen maar doet alsof?',
    template: 'didyouknow',
  },
  {
    id: 'dyk-3',
    type: 'didyouknow',
    skill: 'Zelfregulatie',
    text: 'je brein 90 seconden nodig heeft om een emotie te verwerken? Na die 90 seconden is de rest een keuze.',
    template: 'didyouknow',
  },
  {
    id: 'dyk-4',
    type: 'didyouknow',
    skill: 'Grenzen',
    text: 'kinderen grenzen niet testen om je gek te maken, maar om te controleren of de wereld veilig is?',
    template: 'didyouknow',
  },
  {
    id: 'dyk-5',
    type: 'didyouknow',
    skill: 'Autonomie',
    text: 'een kind dat op 4-jarige leeftijd zelf zijn schoenen leert strikken, meer zelfvertrouwen ontwikkelt dan een kind dat op zijn 8e nog geholpen wordt?',
    template: 'didyouknow',
  },
  {
    id: 'dyk-6',
    type: 'didyouknow',
    skill: 'Herstel',
    text: 'kinderen die zien dat hun vader sorry zegt, zelf 3x sneller leren om fouten toe te geven?',
    template: 'didyouknow',
  },
  {
    id: 'dyk-7',
    type: 'didyouknow',
    skill: 'Verbinding',
    text: 'de stem van een vader een ander stresshormoon-effect heeft dan de stem van een moeder? Beide zijn nodig.',
    template: 'didyouknow',
  },
  {
    id: 'dyk-8',
    type: 'didyouknow',
    skill: 'Reflectie',
    text: 'je onbewust 80% van je opvoedstijl kopieert van je eigen ouders? Bewustwording is de eerste stap om dat te veranderen.',
    template: 'didyouknow',
  },
  {
    id: 'dyk-9',
    type: 'didyouknow',
    skill: 'Aanwezigheid',
    text: 'het brein van een kind zich anders ontwikkelt als het regelmatig onverdeelde aandacht krijgt? Het versterkt de prefrontale cortex.',
    template: 'didyouknow',
  },
  {
    id: 'dyk-10',
    type: 'didyouknow',
    skill: 'Emotiecoaching',
    text: 'een driftbui bij een kleuter neurologisch vergelijkbaar is met een paniekaanval bij een volwassene? Bestraffen helpt dan niet.',
    template: 'didyouknow',
  },
  {
    id: 'dyk-11',
    type: 'didyouknow',
    skill: 'Zelfregulatie',
    text: 'je hartslag boven de 100 slagen per minuut je vermogen om helder te denken met 50% daalt? Daarom werkt pauzeren.',
    template: 'didyouknow',
  },
  {
    id: 'dyk-12',
    type: 'didyouknow',
    skill: 'Grenzen',
    text: 'het woord "nee" gemiddeld 400 keer per dag klinkt in een gezin met jonge kinderen? Kies welke nee echt telt.',
    template: 'didyouknow',
  },
  {
    id: 'dyk-13',
    type: 'didyouknow',
    skill: 'Verbinding',
    text: 'samen lachen dezelfde hersengebieden activeert als een knuffel? Humor is een krachtige verbinder.',
    template: 'didyouknow',
  },
  {
    id: 'dyk-14',
    type: 'didyouknow',
    skill: 'Autonomie',
    text: 'kinderen die mogen helpen in het huishouden later meer empathie tonen en betere relaties hebben?',
    template: 'didyouknow',
  },
  {
    id: 'dyk-15',
    type: 'didyouknow',
    skill: 'Herstel',
    text: 'een hersteld conflict de band sterker maakt dan wanneer er nooit een conflict was geweest?',
    template: 'didyouknow',
  },
  {
    id: 'dyk-16',
    type: 'didyouknow',
    skill: 'Reflectie',
    text: 'vaders die journalen over hun vaderschap significant minder stress ervaren na 4 weken?',
    template: 'didyouknow',
  },
  {
    id: 'dyk-17',
    type: 'didyouknow',
    skill: 'Aanwezigheid',
    text: 'kinderen het verschil voelen tussen een ouder die fysiek aanwezig is en een ouder die er echt is? Ze gedragen zich anders bij beide.',
    template: 'didyouknow',
  },
  {
    id: 'dyk-18',
    type: 'didyouknow',
    skill: 'Emotiecoaching',
    text: 'jongens in Nederland gemiddeld 30% minder emotiewoorden kennen dan meisjes? Dat is aangeleerd, niet aangeboren.',
    template: 'didyouknow',
  },
  {
    id: 'dyk-19',
    type: 'didyouknow',
    skill: 'Zelfregulatie',
    text: 'je lichaam al 0,2 seconden voor je het bewust merkt reageert op stress? Leer de vroege signalen herkennen.',
    template: 'didyouknow',
  },
  {
    id: 'dyk-20',
    type: 'didyouknow',
    skill: 'Grenzen',
    text: 'kinderen die opgroeien met duidelijke grenzen als volwassene beter hun eigen grenzen kunnen aangeven?',
    template: 'didyouknow',
  },
  {
    id: 'dyk-21',
    type: 'didyouknow',
    skill: 'Verbinding',
    text: 'de puberteit niet betekent dat je kind minder verbinding nodig heeft? Het heeft juist meer nodig, alleen op een andere manier.',
    template: 'didyouknow',
  },
  {
    id: 'dyk-22',
    type: 'didyouknow',
    skill: 'Autonomie',
    text: 'Scandinavische kinderen gemiddeld 2 jaar eerder zelfstandig worden dan kinderen in Zuid-Europa? Vertrouwen speelt daarin een grote rol.',
    template: 'didyouknow',
  },
  {
    id: 'dyk-23',
    type: 'didyouknow',
    skill: 'Herstel',
    text: 'het brein van een kind na een conflict in een verhoogde staat van alertheid blijft tot er herstel plaatsvindt?',
    template: 'didyouknow',
  },
  {
    id: 'dyk-24',
    type: 'didyouknow',
    skill: 'Reflectie',
    text: 'de meeste opvoedpatronen worden doorgegeven via onbewust gedrag, niet via bewuste keuzes?',
    template: 'didyouknow',
  },
  {
    id: 'dyk-25',
    type: 'didyouknow',
    skill: 'Aanwezigheid',
    text: 'spelende vaders andere hersengebieden activeren bij hun kinderen dan spelende moeders? Beide zijn waardevol en uniek.',
    template: 'didyouknow',
  },
  {
    id: 'dyk-26',
    type: 'didyouknow',
    skill: 'Emotiecoaching',
    text: 'het benoemen van een emotie de activiteit in de amygdala direct vermindert? "Name it to tame it" is neurologisch bewezen.',
    template: 'didyouknow',
  },
  {
    id: 'dyk-27',
    type: 'didyouknow',
    skill: 'Zelfregulatie',
    text: 'slaapgebrek hetzelfde effect heeft op je geduld als twee glazen alcohol? Een goed uitgeruste vader is een betere vader.',
    template: 'didyouknow',
  },
  {
    id: 'dyk-28',
    type: 'didyouknow',
    skill: 'Verbinding',
    text: 'het samen doen van alledaagse taken - afwassen, boodschappen, koken - meer verbinding schept dan speciale uitjes?',
    template: 'didyouknow',
  },

  // ════════════════════════════════════════════════════════════════════
  // CHALLENGES (27, ~3-4 per skill)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'chal-aanw-1',
    type: 'challenge',
    skill: 'Aanwezigheid',
    text: '5 minuten per dag telefoon weg als je kind thuiskomt',
    subtitle: 'Kijk wat er verandert in het contact.',
    template: 'challenge',
  },
  {
    id: 'chal-aanw-2',
    type: 'challenge',
    skill: 'Aanwezigheid',
    text: 'Elke dag 10 minuten meespelen met het spel van je kind',
    subtitle: 'Zonder het over te nemen of te sturen.',
    template: 'challenge',
  },
  {
    id: 'chal-aanw-3',
    type: 'challenge',
    skill: 'Aanwezigheid',
    text: 'Een week lang elke avond vragen: "Wat was het mooiste moment van je dag?"',
    subtitle: 'Luister echt naar het antwoord.',
    template: 'challenge',
  },
  {
    id: 'chal-emot-1',
    type: 'challenge',
    skill: 'Emotiecoaching',
    text: 'Benoem deze week elke dag een emotie hardop - van jezelf',
    subtitle: '"Ik voel me blij/gefrustreerd/moe." Je kind leert door jouw voorbeeld.',
    template: 'challenge',
  },
  {
    id: 'chal-emot-2',
    type: 'challenge',
    skill: 'Emotiecoaching',
    text: 'Vervang deze week "Niet huilen" door "Ik zie dat je verdrietig bent"',
    subtitle: 'Let op het verschil in reactie.',
    template: 'challenge',
  },
  {
    id: 'chal-emot-3',
    type: 'challenge',
    skill: 'Emotiecoaching',
    text: 'Vraag je kind elke avond: hoe voelde je je vandaag op school?',
    subtitle: 'Gebruik een schaal van 1-10 als het lastig is om woorden te vinden.',
    template: 'challenge',
  },
  {
    id: 'chal-zelf-1',
    type: 'challenge',
    skill: 'Zelfregulatie',
    text: 'Pauzeer deze week 5 seconden voor je reageert als je kind iets doet wat je irriteert',
    subtitle: 'Tel in stilte tot 5. Reageer dan pas.',
    template: 'challenge',
  },
  {
    id: 'chal-zelf-2',
    type: 'challenge',
    skill: 'Zelfregulatie',
    text: 'Doe 7 dagen lang elke ochtend 2 minuten ademhalingsoefeningen',
    subtitle: 'Start de dag vanuit rust in plaats van haast.',
    template: 'challenge',
  },
  {
    id: 'chal-zelf-3',
    type: 'challenge',
    skill: 'Zelfregulatie',
    text: 'Schrijf elke avond op: wanneer voelde ik vandaag de meeste spanning?',
    subtitle: 'Na een week zie je je patronen.',
    template: 'challenge',
  },
  {
    id: 'chal-gren-1',
    type: 'challenge',
    skill: 'Grenzen',
    text: 'Kies deze week 1 grens en houd die consequent vol - zonder uitzondering',
    subtitle: 'Consistentie is belangrijker dan strengheid.',
    template: 'challenge',
  },
  {
    id: 'chal-gren-2',
    type: 'challenge',
    skill: 'Grenzen',
    text: 'Vervang "Niet doen!" door te zeggen wat je kind wel kan doen',
    subtitle: '"Loop alsjeblieft" in plaats van "Niet rennen!"',
    template: 'challenge',
  },
  {
    id: 'chal-gren-3',
    type: 'challenge',
    skill: 'Grenzen',
    text: 'Geef je kind deze week elke dag een keuze binnen een grens',
    subtitle: '"Wil je je tanden poetsen voor of na het voorlezen?"',
    template: 'challenge',
  },
  {
    id: 'chal-auto-1',
    type: 'challenge',
    skill: 'Autonomie',
    text: 'Laat je kind deze week elke dag een ding zelf doen dat je normaal voor hem doet',
    subtitle: 'Brood smeren, tas inpakken, kleren kiezen.',
    template: 'challenge',
  },
  {
    id: 'chal-auto-2',
    type: 'challenge',
    skill: 'Autonomie',
    text: 'Zeg deze week 5 keer "Wat denk jij?" voor je zelf een antwoord geeft',
    subtitle: 'Je zult verrast zijn door de antwoorden.',
    template: 'challenge',
  },
  {
    id: 'chal-auto-3',
    type: 'challenge',
    skill: 'Autonomie',
    text: 'Laat je kind een maaltijd plannen en helpen koken dit weekend',
    subtitle: 'Geef regie, bied ondersteuning.',
    template: 'challenge',
  },
  {
    id: 'chal-hers-1',
    type: 'challenge',
    skill: 'Herstel',
    text: 'Zeg deze week bewust sorry als je een fout maakt tegenover je kind',
    subtitle: 'Benoem wat je deed, hoe het voor je kind was, en wat je anders wilt doen.',
    template: 'challenge',
  },
  {
    id: 'chal-hers-2',
    type: 'challenge',
    skill: 'Herstel',
    text: 'Vraag je kind na een conflict: "Hoe voelde dat voor jou?"',
    subtitle: 'Luister zonder je te verdedigen.',
    template: 'challenge',
  },
  {
    id: 'chal-hers-3',
    type: 'challenge',
    skill: 'Herstel',
    text: 'Herstel deze week elk conflict binnen een uur in plaats van het te laten liggen',
    subtitle: 'Snelheid van herstel maakt het verschil.',
    template: 'challenge',
  },
  {
    id: 'chal-verb-1',
    type: 'challenge',
    skill: 'Verbinding',
    text: 'Plan deze week een activiteit alleen met je kind, zonder andere gezinsleden',
    subtitle: 'Het hoeft niet bijzonder te zijn. Een wandeling is genoeg.',
    template: 'challenge',
  },
  {
    id: 'chal-verb-2',
    type: 'challenge',
    skill: 'Verbinding',
    text: 'Vertel je kind deze week een verhaal over toen jij jong was',
    subtitle: 'Laat zien dat jij ook kind bent geweest.',
    template: 'challenge',
  },
  {
    id: 'chal-verb-3',
    type: 'challenge',
    skill: 'Verbinding',
    text: 'Stuur je tiener elke dag een kort berichtje - niet om te controleren, maar om verbinding te maken',
    subtitle: '"Dacht aan je." Meer hoeft niet.',
    template: 'challenge',
  },
  {
    id: 'chal-verb-4',
    type: 'challenge',
    skill: 'Verbinding',
    text: 'Eet deze week minstens 4 keer samen aan tafel, zonder schermen',
    subtitle: 'Samen eten is een van de krachtigste verbinders die er is.',
    template: 'challenge',
  },
  {
    id: 'chal-refl-1',
    type: 'challenge',
    skill: 'Reflectie',
    text: 'Schrijf elke avond 3 dingen op die goed gingen als vader vandaag',
    subtitle: 'Reflectie is niet alleen kijken naar wat beter kan.',
    template: 'challenge',
  },
  {
    id: 'chal-refl-2',
    type: 'challenge',
    skill: 'Reflectie',
    text: 'Vraag je partner deze week: "Hoe kom ik over als vader?"',
    subtitle: 'Luister met een open houding.',
    template: 'challenge',
  },
  {
    id: 'chal-refl-3',
    type: 'challenge',
    skill: 'Reflectie',
    text: 'Schrijf een brief aan je toekomstige zelf over de vader die je wilt zijn over 5 jaar',
    subtitle: 'Bewaar hem en lees hem volgend jaar terug.',
    template: 'challenge',
  },
  {
    id: 'chal-refl-4',
    type: 'challenge',
    skill: 'Reflectie',
    text: 'Benoem deze week een patroon uit je eigen opvoeding dat je wilt doorbreken',
    subtitle: 'Schrijf op wat je in plaats daarvan wilt doen.',
    template: 'challenge',
  },
  {
    id: 'chal-zelf-4',
    type: 'challenge',
    skill: 'Zelfregulatie',
    text: 'Ga deze week een keer bewust eerder naar bed op een doordeweekse avond',
    subtitle: 'Slaap is je geheime opvoedwapen.',
    template: 'challenge',
  },

  // ════════════════════════════════════════════════════════════════════
  // COMPARISONS - Niet vs Wel (28)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'comp-1',
    type: 'comparison',
    skill: 'Emotiecoaching',
    text: 'Stop met huilen!',
    subtitle: 'Ik zie dat je verdrietig bent. Mag ik bij je zitten?',
    template: 'comparison',
  },
  {
    id: 'comp-2',
    type: 'comparison',
    skill: 'Grenzen',
    text: 'Omdat ik het zeg!',
    subtitle: 'De regel is: eerst opruimen, dan spelen. Dat weet je.',
    template: 'comparison',
  },
  {
    id: 'comp-3',
    type: 'comparison',
    skill: 'Emotiecoaching',
    text: 'Stel je niet zo aan.',
    subtitle: 'Ik begrijp dat dit moeilijk voor je is.',
    template: 'comparison',
  },
  {
    id: 'comp-4',
    type: 'comparison',
    skill: 'Autonomie',
    text: 'Laat mij maar, jij kunt dat nog niet.',
    subtitle: 'Probeer het maar. Ik help je als je vastloopt.',
    template: 'comparison',
  },
  {
    id: 'comp-5',
    type: 'comparison',
    skill: 'Herstel',
    text: 'Ik heb ook niks verkeerds gedaan.',
    subtitle: 'Sorry dat ik zo reageerde. Dat was niet eerlijk.',
    template: 'comparison',
  },
  {
    id: 'comp-6',
    type: 'comparison',
    skill: 'Verbinding',
    text: 'Hoe was school? Goed? Oké.',
    subtitle: 'Wat was het grappigste dat er vandaag gebeurde?',
    template: 'comparison',
  },
  {
    id: 'comp-7',
    type: 'comparison',
    skill: 'Zelfregulatie',
    text: 'IK ZEI TOCH DAT JE MOEST STOPPEN!',
    subtitle: 'Ik merk dat ik boos word. Even pauze, ik kom zo terug.',
    template: 'comparison',
  },
  {
    id: 'comp-8',
    type: 'comparison',
    skill: 'Reflectie',
    text: 'Zo ben ik nu eenmaal.',
    subtitle: 'Ik merk dat ik dit patroon heb. Ik wil het anders doen.',
    template: 'comparison',
  },
  {
    id: 'comp-9',
    type: 'comparison',
    skill: 'Aanwezigheid',
    text: 'Wacht even, ik ben bezig.',
    subtitle: 'Ik maak dit even af en dan ben ik er helemaal voor je.',
    template: 'comparison',
  },
  {
    id: 'comp-10',
    type: 'comparison',
    skill: 'Emotiecoaching',
    text: 'Jongens huilen niet.',
    subtitle: 'Het is oké om te huilen. Iedereen wordt weleens verdrietig.',
    template: 'comparison',
  },
  {
    id: 'comp-11',
    type: 'comparison',
    skill: 'Grenzen',
    text: 'Vooruit dan maar, voor deze ene keer.',
    subtitle: 'Ik begrijp dat je het vervelend vindt, maar de afspraak staat.',
    template: 'comparison',
  },
  {
    id: 'comp-12',
    type: 'comparison',
    skill: 'Autonomie',
    text: 'Doe het zo, dat is beter.',
    subtitle: 'Interessant hoe je dat aanpakt. Wat was je plan?',
    template: 'comparison',
  },
  {
    id: 'comp-13',
    type: 'comparison',
    skill: 'Herstel',
    text: 'Sorry, maar jij begon.',
    subtitle: 'Ik had anders moeten reageren. Sorry daarvoor.',
    template: 'comparison',
  },
  {
    id: 'comp-14',
    type: 'comparison',
    skill: 'Verbinding',
    text: 'Ga maar lekker op je kamer.',
    subtitle: 'Zullen we samen even een rondje lopen?',
    template: 'comparison',
  },
  {
    id: 'comp-15',
    type: 'comparison',
    skill: 'Zelfregulatie',
    text: 'Je maakt me gek!',
    subtitle: 'Ik voel dat ik gefrustreerd raak. Dat ligt niet aan jou.',
    template: 'comparison',
  },
  {
    id: 'comp-16',
    type: 'comparison',
    skill: 'Reflectie',
    text: 'In mijn tijd kregen we gewoon een tik.',
    subtitle: 'Ik wil het anders doen dan hoe ik het zelf meegemaakt heb.',
    template: 'comparison',
  },
  {
    id: 'comp-17',
    type: 'comparison',
    skill: 'Aanwezigheid',
    text: 'Hmm ja, leuk (terwijl je op je telefoon kijkt).',
    subtitle: 'Wacht, ik leg mijn telefoon weg. Vertel het nog eens.',
    template: 'comparison',
  },
  {
    id: 'comp-18',
    type: 'comparison',
    skill: 'Emotiecoaching',
    text: 'Er is niks om bang voor te zijn.',
    subtitle: 'Ik snap dat dit eng voelt. Zal ik bij je blijven?',
    template: 'comparison',
  },
  {
    id: 'comp-19',
    type: 'comparison',
    skill: 'Grenzen',
    text: 'Als je niet luistert, krijg je straf!',
    subtitle: 'Als je nu niet opruimt, dan doen we het samen na het eten. Maar het moet wel gebeuren.',
    template: 'comparison',
  },
  {
    id: 'comp-20',
    type: 'comparison',
    skill: 'Autonomie',
    text: 'Dat kun je nog niet, je bent te klein.',
    subtitle: 'Dat is best lastig. Zullen we het stap voor stap proberen?',
    template: 'comparison',
  },
  {
    id: 'comp-21',
    type: 'comparison',
    skill: 'Herstel',
    text: 'We praten er niet meer over.',
    subtitle: 'Ik wil het er nog even over hebben. Hoe voelde dat voor jou?',
    template: 'comparison',
  },
  {
    id: 'comp-22',
    type: 'comparison',
    skill: 'Verbinding',
    text: 'Je doet maar wat je wilt.',
    subtitle: 'Ik merk dat we langs elkaar heen leven. Zullen we vanavond even praten?',
    template: 'comparison',
  },
  {
    id: 'comp-23',
    type: 'comparison',
    skill: 'Zelfregulatie',
    text: 'Ik tel tot drie! Een... twee...',
    subtitle: 'Ik ga even rustig ademhalen. Dan praten we hierover.',
    template: 'comparison',
  },
  {
    id: 'comp-24',
    type: 'comparison',
    skill: 'Aanwezigheid',
    text: 'Niet nu, papa moet werken.',
    subtitle: 'Ik moet nog even werken. Om 5 uur ben ik klaar en dan spelen we samen.',
    template: 'comparison',
  },
  {
    id: 'comp-25',
    type: 'comparison',
    skill: 'Emotiecoaching',
    text: 'Wat is er nou weer?',
    subtitle: 'Ik zie dat er iets is. Wil je erover praten?',
    template: 'comparison',
  },
  {
    id: 'comp-26',
    type: 'comparison',
    skill: 'Grenzen',
    text: 'Je mag niet boos zijn op mij!',
    subtitle: 'Je mag best boos zijn. Maar we gaan niet schreeuwen naar elkaar.',
    template: 'comparison',
  },
  {
    id: 'comp-27',
    type: 'comparison',
    skill: 'Reflectie',
    text: 'Ik doe toch mijn best!',
    subtitle: 'Ik merk dat dit een gevoelig punt voor me is. Waarom eigenlijk?',
    template: 'comparison',
  },
  {
    id: 'comp-28',
    type: 'comparison',
    skill: 'Verbinding',
    text: 'Je vertelt mij ook nooit iets.',
    subtitle: 'Ik zou graag meer willen weten over hoe het met je gaat. Geen druk.',
    template: 'comparison',
  },

  // ════════════════════════════════════════════════════════════════════
  // QUOTES (24)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'quote-1',
    type: 'quote',
    skill: 'Aanwezigheid',
    text: 'Een kind hoeft geen perfecte vader. Het heeft een aanwezige vader nodig.',
    template: 'quote',
  },
  {
    id: 'quote-2',
    type: 'quote',
    skill: 'Grenzen',
    text: 'Grenzen stellen is geen liefde weigeren. Het is liefde in actie.',
    template: 'quote',
  },
  {
    id: 'quote-3',
    type: 'quote',
    skill: 'Herstel',
    text: 'De kracht van een vader zit niet in het nooit falen, maar in het altijd terugkomen.',
    template: 'quote',
  },
  {
    id: 'quote-4',
    type: 'quote',
    skill: 'Emotiecoaching',
    text: 'Je hoeft de storm niet te stoppen. Je hoeft er alleen doorheen te staan, samen met je kind.',
    template: 'quote',
  },
  {
    id: 'quote-5',
    type: 'quote',
    skill: 'Zelfregulatie',
    text: 'De rust die jij uitstraalt, is de rust die je kind voelt.',
    template: 'quote',
  },
  {
    id: 'quote-6',
    type: 'quote',
    skill: 'Verbinding',
    text: 'Je kind zal niet onthouden wat je zei. Het onthoudt hoe het zich voelde als jij er was.',
    template: 'quote',
  },
  {
    id: 'quote-7',
    type: 'quote',
    skill: 'Autonomie',
    text: 'Loslaten is niet opgeven. Het is vertrouwen dat je genoeg hebt meegegeven.',
    template: 'quote',
  },
  {
    id: 'quote-8',
    type: 'quote',
    skill: 'Reflectie',
    text: 'De beste investering in je kind is het werk dat je aan jezelf doet.',
    template: 'quote',
  },
  {
    id: 'quote-9',
    type: 'quote',
    skill: 'Aanwezigheid',
    text: 'Twee minuten echt. Dat is wat je kind nodig heeft. Niet twee uur halfbakken.',
    template: 'quote',
  },
  {
    id: 'quote-10',
    type: 'quote',
    skill: 'Emotiecoaching',
    text: 'Alle gevoelens zijn welkom. Niet al het gedrag is oké. Dat onderscheid is je belangrijkste les.',
    template: 'quote',
  },
  {
    id: 'quote-11',
    type: 'quote',
    skill: 'Zelfregulatie',
    text: 'Kalmte is geen gave. Het is een vaardigheid die je kunt trainen, elke dag opnieuw.',
    template: 'quote',
  },
  {
    id: 'quote-12',
    type: 'quote',
    skill: 'Grenzen',
    text: 'Een kind dat nooit nee hoort, leert nooit om met tegenslagen om te gaan.',
    template: 'quote',
  },
  {
    id: 'quote-13',
    type: 'quote',
    skill: 'Herstel',
    text: 'Sorry zeggen naar je kind is geen stap terug. Het is een stap vooruit.',
    template: 'quote',
  },
  {
    id: 'quote-14',
    type: 'quote',
    skill: 'Verbinding',
    text: 'Verbinding is geen programma dat je installeert. Het is een tuin die je elke dag een beetje water geeft.',
    template: 'quote',
  },
  {
    id: 'quote-15',
    type: 'quote',
    skill: 'Autonomie',
    text: 'De moeilijkste taak van een vader: aan de zijlijn staan terwijl je kind leert vallen.',
    template: 'quote',
  },
  {
    id: 'quote-16',
    type: 'quote',
    skill: 'Reflectie',
    text: 'Je kunt niet bewust opvoeden als je onbewust leeft.',
    template: 'quote',
  },
  {
    id: 'quote-17',
    type: 'quote',
    skill: 'Aanwezigheid',
    text: 'Je kind groeit sneller dan je denkt. Vandaag is de dag om er te zijn.',
    template: 'quote',
  },
  {
    id: 'quote-18',
    type: 'quote',
    skill: 'Emotiecoaching',
    text: 'Een vader die zegt "Ik snap dat je boos bent" geeft zijn kind meer dan een vader die zegt "Hou op."',
    template: 'quote',
  },
  {
    id: 'quote-19',
    type: 'quote',
    skill: 'Zelfregulatie',
    text: 'Je kunt je kind niet leren om kalm te blijven als jij zelf ontploft bij elke tegenslag.',
    template: 'quote',
  },
  {
    id: 'quote-20',
    type: 'quote',
    skill: 'Verbinding',
    text: 'De sterkste band ontstaat niet in de makkelijke momenten, maar in de moeilijke.',
    template: 'quote',
  },
  {
    id: 'quote-21',
    type: 'quote',
    skill: 'Grenzen',
    text: 'Consequent zijn is vermoeiend. Maar het alternatief - inconsequent zijn - kost uiteindelijk meer energie.',
    template: 'quote',
  },
  {
    id: 'quote-22',
    type: 'quote',
    skill: 'Herstel',
    text: 'Het mooiste wat je je kind kunt laten zien: dat fouten geen eindpunt zijn, maar een beginpunt.',
    template: 'quote',
  },
  {
    id: 'quote-23',
    type: 'quote',
    skill: 'Reflectie',
    text: 'De vader die je bent geworden, is niet de vader die je hoeft te blijven.',
    subtitle: 'Verandering begint bij bewustwording.',
    template: 'quote',
  },
  {
    id: 'quote-24',
    type: 'quote',
    skill: 'Autonomie',
    text: 'Beschermen is een instinct. Loslaten is een keuze. Beide zijn liefde.',
    template: 'quote',
  },

  // ════════════════════════════════════════════════════════════════════
  // NEW TIPS - Aanwezigheid (5)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'tip-aanw-11',
    type: 'tip',
    skill: 'Aanwezigheid',
    text: 'Zet een dagelijks alarm op het moment dat je kind thuiskomt. Het herinnert je om even te stoppen met wat je doet.',
    template: 'tip',
  },
  {
    id: 'tip-aanw-12',
    type: 'tip',
    skill: 'Aanwezigheid',
    text: 'Loop mee naar school als het kan. De wandeling erheen levert vaak betere gesprekken op dan het avondeten.',
    template: 'tip',
  },
  {
    id: 'tip-aanw-13',
    type: 'tip',
    skill: 'Aanwezigheid',
    text: 'Merk je dat je gedachten afdwalen tijdens het spelen? Beschrijf hardop wat je kind doet. Het brengt je terug in het moment.',
    template: 'tip',
  },
  {
    id: 'tip-aanw-14',
    type: 'tip',
    skill: 'Aanwezigheid',
    text: 'Zet notificaties uit tussen 18:00 en 20:00. Twee uur zonder afleiding geeft je kind het signaal dat het voorrang heeft.',
    template: 'tip',
  },
  {
    id: 'tip-aanw-15',
    type: 'tip',
    skill: 'Aanwezigheid',
    text: 'Wees ook aanwezig bij de saaie momenten. Niet alleen het voetbaltoernooi, maar ook het oefenen in de achtertuin telt.',
    template: 'tip',
  },

  // ════════════════════════════════════════════════════════════════════
  // NEW TIPS - Emotiecoaching (5)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'tip-emot-11',
    type: 'tip',
    skill: 'Emotiecoaching',
    text: 'Teken samen een "emotiekaart" van het lichaam. Waar voelt je kind boosheid? Waar zit spanning? Het maakt abstracte gevoelens tastbaar.',
    template: 'tip',
  },
  {
    id: 'tip-emot-12',
    type: 'tip',
    skill: 'Emotiecoaching',
    text: 'Als je kind zegt "Ik haat je", hoor dan wat erachter zit. Vaak betekent het: ik ben gefrustreerd en jij bent veilig genoeg om dat tegen te zeggen.',
    template: 'tip',
  },
  {
    id: 'tip-emot-13',
    type: 'tip',
    skill: 'Emotiecoaching',
    text: 'Geef emoties een score van 1 tot 10 samen met je kind. Het leert nuance: niet elke boosheid is een 10.',
    template: 'tip',
  },
  {
    id: 'tip-emot-14',
    type: 'tip',
    skill: 'Emotiecoaching',
    text: 'Reageer niet op het gedrag, maar op het gevoel eronder. Een schoppend kind is vaak een bang of verdrietig kind.',
    template: 'tip',
  },
  {
    id: 'tip-emot-15',
    type: 'tip',
    skill: 'Emotiecoaching',
    text: 'Deel je eigen emoties in lagen. "Eerst was ik boos, maar eigenlijk was ik bezorgd." Zo leert je kind dat gevoelens gelaagd zijn.',
    template: 'tip',
  },

  // ════════════════════════════════════════════════════════════════════
  // NEW TIPS - Zelfregulatie (5)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'tip-zelf-11',
    type: 'tip',
    skill: 'Zelfregulatie',
    text: 'Heb een codewoord met je partner. Als een van jullie het zegt, betekent het: neem jij het over, ik heb even pauze nodig.',
    template: 'tip',
  },
  {
    id: 'tip-zelf-12',
    type: 'tip',
    skill: 'Zelfregulatie',
    text: 'Pak een glas water als je merkt dat je geprikkeld raakt. De fysieke handeling doorbreekt het automatische reactiepatroon.',
    template: 'tip',
  },
  {
    id: 'tip-zelf-13',
    type: 'tip',
    skill: 'Zelfregulatie',
    text: 'Verlaag je stemvolume bewust als een situatie escaleert. Fluisteren dwingt je kind om te luisteren en kalmeert jullie allebei.',
    template: 'tip',
  },
  {
    id: 'tip-zelf-14',
    type: 'tip',
    skill: 'Zelfregulatie',
    text: 'Beweeg overdag. Dertig minuten wandelen of fietsen verlaagt je stressniveau de rest van de dag merkbaar.',
    template: 'tip',
  },
  {
    id: 'tip-zelf-15',
    type: 'tip',
    skill: 'Zelfregulatie',
    text: 'Zeg hardop wat je voelt: "Ik merk dat ik ongeduldig word." Het benoemen alleen al remt de escalatie.',
    template: 'tip',
  },

  // ════════════════════════════════════════════════════════════════════
  // NEW TIPS - Grenzen (5)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'tip-gren-11',
    type: 'tip',
    skill: 'Grenzen',
    text: 'Geef een waarschuwing voor de overgang. "Over vijf minuten gaan we eten" werkt beter dan "Nu aan tafel!"',
    template: 'tip',
  },
  {
    id: 'tip-gren-12',
    type: 'tip',
    skill: 'Grenzen',
    text: 'Maak een vast ochtendritueel met duidelijke stappen. Structuur vervangt discussie: na het aankleden wordt er ontbeten.',
    template: 'tip',
  },
  {
    id: 'tip-gren-13',
    type: 'tip',
    skill: 'Grenzen',
    text: 'Evalueer je regels samen met je kind als het ouder wordt. Een grens die niet meer past, verliest zijn waarde.',
    template: 'tip',
  },
  {
    id: 'tip-gren-14',
    type: 'tip',
    skill: 'Grenzen',
    text: 'Gebruik "wanneer... dan" in plaats van dreigen. "Wanneer je kamer opgeruimd is, dan kun je naar buiten." Helder en zonder drama.',
    template: 'tip',
  },
  {
    id: 'tip-gren-15',
    type: 'tip',
    skill: 'Grenzen',
    text: 'Schreeuw niet over grenzen. Een grens die je fluisterend uitspreekt, maakt meer indruk dan een die je brult.',
    template: 'tip',
  },

  // ════════════════════════════════════════════════════════════════════
  // NEW TIPS - Autonomie (5)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'tip-auto-11',
    type: 'tip',
    skill: 'Autonomie',
    text: 'Geef je kind een eigen wekker. Zelf op tijd opstaan is een kleine stap die veel zelfvertrouwen bouwt.',
    template: 'tip',
  },
  {
    id: 'tip-auto-12',
    type: 'tip',
    skill: 'Autonomie',
    text: 'Vraag na een schoolproject niet "Welk cijfer heb je?" maar "Wat heb je geleerd?" Het verschuift de focus naar groei.',
    template: 'tip',
  },
  {
    id: 'tip-auto-13',
    type: 'tip',
    skill: 'Autonomie',
    text: 'Laat je kind fouten maken in een veilige omgeving. Een mislukt recept is een betere les dan een perfect recept van papa.',
    template: 'tip',
  },
  {
    id: 'tip-auto-14',
    type: 'tip',
    skill: 'Autonomie',
    text: 'Geef je tiener een eigen budget voor schoolspullen of kleding. Het leert financieel denken zonder dat de gevolgen groot zijn.',
    template: 'tip',
  },
  {
    id: 'tip-auto-15',
    type: 'tip',
    skill: 'Autonomie',
    text: 'Stop met zinnen die beginnen met "Je moet..." Probeer "Wat als je..." Het eerste blokkeert, het tweede activeert.',
    template: 'tip',
  },

  // ════════════════════════════════════════════════════════════════════
  // NEW TIPS - Herstel (5)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'tip-hers-11',
    type: 'tip',
    skill: 'Herstel',
    text: 'Ga niet in de verdediging als je kind zegt dat je iets verkeerd deed. Zeg: "Dank je dat je het me vertelt."',
    template: 'tip',
  },
  {
    id: 'tip-hers-12',
    type: 'tip',
    skill: 'Herstel',
    text: 'Gebruik fysiek contact bij herstel. Een hand op de schouder of een knuffel zegt soms meer dan woorden.',
    template: 'tip',
  },
  {
    id: 'tip-hers-13',
    type: 'tip',
    skill: 'Herstel',
    text: 'Maak een "herstart-ritueel" voor na een ruzie. Een high five, een speciaal gebaar. Het markeert het moment dat het weer goed is.',
    template: 'tip',
  },
  {
    id: 'tip-hers-14',
    type: 'tip',
    skill: 'Herstel',
    text: 'Schrijf een briefje als praten lastig is. "Sorry van daarnet. Ik hou van je." Een paar woorden op papier kunnen veel rechtzetten.',
    template: 'tip',
  },
  {
    id: 'tip-hers-15',
    type: 'tip',
    skill: 'Herstel',
    text: 'Herstel ook als je kind niet boos lijkt. Kinderen stoppen gevoelens soms weg. Jouw initiatief laat zien dat het veilig is om ze te uiten.',
    template: 'tip',
  },

  // ════════════════════════════════════════════════════════════════════
  // NEW TIPS - Verbinding (5)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'tip-verb-11',
    type: 'tip',
    skill: 'Verbinding',
    text: 'Maak een playlist samen. Muziek delen creëert een gedeelde taal die verder gaat dan woorden.',
    template: 'tip',
  },
  {
    id: 'tip-verb-12',
    type: 'tip',
    skill: 'Verbinding',
    text: 'Ga samen naar buiten zonder bestemming. De beste gesprekken ontstaan onderweg, niet bij aankomst.',
    template: 'tip',
  },
  {
    id: 'tip-verb-13',
    type: 'tip',
    skill: 'Verbinding',
    text: 'Leer iets van je kind. Laat het jou uitleggen hoe een game werkt of wie die artiest is. Rollen omdraaien versterkt de band.',
    template: 'tip',
  },
  {
    id: 'tip-verb-14',
    type: 'tip',
    skill: 'Verbinding',
    text: 'Maak een foto van een gewoon moment samen en bewaar het. Over tien jaar is het een schat.',
    template: 'tip',
  },
  {
    id: 'tip-verb-15',
    type: 'tip',
    skill: 'Verbinding',
    text: 'Zeg regelmatig tegen je kind waarom je trots op hem bent. Niet op prestaties, maar op wie hij is als mens.',
    template: 'tip',
  },

  // ════════════════════════════════════════════════════════════════════
  // NEW TIPS - Reflectie (5)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'tip-refl-11',
    type: 'tip',
    skill: 'Reflectie',
    text: 'Houd een "vaderlogboek" bij van een zin per dag. Na een maand zie je patronen die je anders had gemist.',
    template: 'tip',
  },
  {
    id: 'tip-refl-12',
    type: 'tip',
    skill: 'Reflectie',
    text: 'Stel jezelf regelmatig de vraag: doe ik dit voor mijn kind, of voor mijn eigen ego? Het antwoord is verhelderend.',
    template: 'tip',
  },
  {
    id: 'tip-refl-13',
    type: 'tip',
    skill: 'Reflectie',
    text: 'Zoek een andere vader om eerlijk mee te praten. Niet om advies te geven, maar om te spiegelen.',
    template: 'tip',
  },
  {
    id: 'tip-refl-14',
    type: 'tip',
    skill: 'Reflectie',
    text: 'Vraag je kind hoe het jou als vader ervaart. Kinderen vanaf 6 jaar geven verrassend eerlijke en waardevolle feedback.',
    template: 'tip',
  },
  {
    id: 'tip-refl-15',
    type: 'tip',
    skill: 'Reflectie',
    text: 'Let op momenten waarop je automatisch reageert. Juist daar zit de ruimte voor groei: tussen de prikkel en je reactie.',
    template: 'tip',
  },

  // ════════════════════════════════════════════════════════════════════
  // NEW STATISTICS (18)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'stat-33',
    type: 'stat',
    skill: 'Aanwezigheid',
    text: 'Kinderen die dagelijks met hun vader spelen, scoren 40% hoger op sociaal-emotionele vaardigheden.',
    subtitle: 'NICHD Study of Early Child Care',
    template: 'stat',
  },
  {
    id: 'stat-34',
    type: 'stat',
    skill: 'Emotiecoaching',
    text: 'Kinderen met emotioneel beschikbare vaders hebben op volwassen leeftijd 50% minder kans op angststoornissen.',
    subtitle: 'Journal of Abnormal Child Psychology',
    template: 'stat',
  },
  {
    id: 'stat-35',
    type: 'stat',
    skill: 'Zelfregulatie',
    text: 'Vaders die hun woede beheersen in het bijzijn van hun kinderen verlagen het stressniveau van het hele gezin.',
    subtitle: 'Family Process Journal, 2021',
    template: 'stat',
  },
  {
    id: 'stat-36',
    type: 'stat',
    skill: 'Grenzen',
    text: 'Kinderen met voorspelbare routines slapen gemiddeld 45 minuten langer per nacht dan kinderen zonder vaste structuur.',
    subtitle: 'Sleep Medicine Reviews, 2019',
    template: 'stat',
  },
  {
    id: 'stat-37',
    type: 'stat',
    skill: 'Autonomie',
    text: 'Kinderen die op jonge leeftijd kleine beslissingen mogen nemen, zijn als tiener 35% beter in het maken van verantwoorde keuzes.',
    subtitle: 'Developmental Psychology, 2020',
    template: 'stat',
  },
  {
    id: 'stat-38',
    type: 'stat',
    skill: 'Herstel',
    text: 'In gezinnen waar ouders actief herstellen na conflicten, is de kans op emotionele problemen bij kinderen 40% lager.',
    subtitle: 'Journal of Marriage and Family',
    template: 'stat',
  },
  {
    id: 'stat-39',
    type: 'stat',
    skill: 'Verbinding',
    text: 'Tieners die wekelijks een-op-een tijd doorbrengen met hun vader, hebben 45% minder kans op middelengebruik.',
    subtitle: 'Pediatrics Journal, 2018',
    template: 'stat',
  },
  {
    id: 'stat-40',
    type: 'stat',
    skill: 'Reflectie',
    text: 'Ouders die reflecteren op hun eigen opvoeding zijn 3 keer vaker in staat om ongewenste patronen te doorbreken.',
    subtitle: 'Adult Attachment Interview Research',
    template: 'stat',
  },
  {
    id: 'stat-41',
    type: 'stat',
    skill: 'Verbinding',
    text: 'Kinderen die hun vader als emotioneel beschikbaar ervaren, rapporteren 60% meer levenstevredenheid als jongvolwassene.',
    subtitle: 'Journal of Positive Psychology, 2019',
    template: 'stat',
  },
  {
    id: 'stat-42',
    type: 'stat',
    skill: 'Aanwezigheid',
    text: '65% van de kinderen noemt "samen iets doen" als het belangrijkste wat hun vader voor hen doet.',
    subtitle: 'Kinderombudsman Nederland, 2020',
    template: 'stat',
  },
  {
    id: 'stat-43',
    type: 'stat',
    skill: 'Zelfregulatie',
    text: 'Ouders die regelmatig mediteren of ademhalingsoefeningen doen, rapporteren 55% minder opvoedstress.',
    subtitle: 'Mindful Parenting Study, Universiteit van Amsterdam',
    template: 'stat',
  },
  {
    id: 'stat-44',
    type: 'stat',
    skill: 'Emotiecoaching',
    text: 'Kinderen die thuis leren praten over emoties, worden op school 30% minder vaak gepest.',
    subtitle: 'Social Development Journal, 2021',
    template: 'stat',
  },
  {
    id: 'stat-45',
    type: 'stat',
    skill: 'Grenzen',
    text: 'Kinderen die grenzen met uitleg krijgen, vertonen 50% meer medewerking dan kinderen die alleen een verbod horen.',
    subtitle: 'Parenting: Science and Practice',
    template: 'stat',
  },
  {
    id: 'stat-46',
    type: 'stat',
    skill: 'Herstel',
    text: '90% van de kinderen vergeeft hun ouder sneller als het excuus specifiek is in plaats van algemeen.',
    subtitle: 'Child Development, 2022',
    template: 'stat',
  },
  {
    id: 'stat-47',
    type: 'stat',
    skill: 'Autonomie',
    text: 'Kinderen die huishoudelijke taken doen, presteren later gemiddeld beter op de arbeidsmarkt.',
    subtitle: 'Harvard Grant Study, vervolgstudie',
    template: 'stat',
  },
  {
    id: 'stat-48',
    type: 'stat',
    skill: 'Reflectie',
    text: 'Vaders die hun eigen jeugdervaringen verwerkt hebben, bieden hun kinderen 4 keer vaker een veilige hechting.',
    subtitle: 'Attachment and Human Development',
    template: 'stat',
  },
  {
    id: 'stat-49',
    type: 'stat',
    skill: 'Verbinding',
    text: 'Fysiek contact tussen vader en kind - knuffels, stoeipartijen - verlaagt het cortisolgehalte bij beiden.',
    subtitle: 'Psychoneuroendocrinology, 2020',
    template: 'stat',
  },
  {
    id: 'stat-50',
    type: 'stat',
    skill: 'Aanwezigheid',
    text: 'Vaders in Nederland nemen gemiddeld 6 weken ouderschapsverlof op. Vaders die dat doen, zijn 5 jaar later nog steeds meer betrokken.',
    subtitle: 'SCP Emancipatiemonitor, 2023',
    template: 'stat',
  },

  // ════════════════════════════════════════════════════════════════════
  // NEW WIST JE DAT / DID YOU KNOW (12)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'dyk-29',
    type: 'didyouknow',
    skill: 'Aanwezigheid',
    text: 'kinderen die hun vader zien lezen, 2 keer meer kans hebben om zelf een leesgewoonte te ontwikkelen?',
    template: 'didyouknow',
  },
  {
    id: 'dyk-30',
    type: 'didyouknow',
    skill: 'Emotiecoaching',
    text: 'het brein van een kind pas rond het 25e levensjaar volledig ontwikkeld is? De prefrontale cortex - verantwoordelijk voor impulscontrole - rijpt als laatste.',
    template: 'didyouknow',
  },
  {
    id: 'dyk-31',
    type: 'didyouknow',
    skill: 'Zelfregulatie',
    text: 'je stembanden zich aanspannen als je gestrest bent? Kinderen horen spanning in je stem, zelfs als je woorden rustig zijn.',
    template: 'didyouknow',
  },
  {
    id: 'dyk-32',
    type: 'didyouknow',
    skill: 'Grenzen',
    text: 'kinderen die opgroeien zonder grenzen vaker last hebben van faalangst? Structuur geeft het brein houvast.',
    template: 'didyouknow',
  },
  {
    id: 'dyk-33',
    type: 'didyouknow',
    skill: 'Autonomie',
    text: 'peuters gemiddeld 200 keer per dag "nee" horen? Maar dat ze beter leren van uitleg dan van verboden.',
    template: 'didyouknow',
  },
  {
    id: 'dyk-34',
    type: 'didyouknow',
    skill: 'Herstel',
    text: 'het stresshormoon cortisol bij kinderen tot 45 minuten verhoogd blijft na een conflict? Herstel brengt het lichaam sneller in balans.',
    template: 'didyouknow',
  },
  {
    id: 'dyk-35',
    type: 'didyouknow',
    skill: 'Verbinding',
    text: 'vaders die samen met hun kind koken een sterkere band opbouwen dan vaders die samen tv kijken? Actieve bezigheden verbinden dieper.',
    template: 'didyouknow',
  },
  {
    id: 'dyk-36',
    type: 'didyouknow',
    skill: 'Reflectie',
    text: 'de toon waarop je ouders tegen je spraken als kind, de stem is geworden waarmee je nu tegen jezelf praat?',
    template: 'didyouknow',
  },
  {
    id: 'dyk-37',
    type: 'didyouknow',
    skill: 'Aanwezigheid',
    text: 'stoeipartijen met papa een van de beste manieren zijn voor kinderen om grenzen te leren en emoties te reguleren?',
    template: 'didyouknow',
  },
  {
    id: 'dyk-38',
    type: 'didyouknow',
    skill: 'Emotiecoaching',
    text: 'kinderen die opgroeien met een emotioneel open vader, later zelf betere romantische relaties hebben?',
    template: 'didyouknow',
  },
  {
    id: 'dyk-39',
    type: 'didyouknow',
    skill: 'Zelfregulatie',
    text: 'een wandeling van 10 minuten in de buitenlucht dezelfde kalmerende werking heeft als een lichte dosis medicatie tegen angst?',
    template: 'didyouknow',
  },
  {
    id: 'dyk-40',
    type: 'didyouknow',
    skill: 'Verbinding',
    text: 'kinderen de geur van hun vader herkennen en dat dit een kalmerend effect heeft, zelfs als papa er niet is?',
    template: 'didyouknow',
  },

  // ════════════════════════════════════════════════════════════════════
  // NEW CHALLENGES (13)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'chal-aanw-4',
    type: 'challenge',
    skill: 'Aanwezigheid',
    text: 'Breng je kind deze week elke dag naar school of haal het op - zonder telefoon in je hand',
    subtitle: 'Gebruik de looptijd als gesprekstijd.',
    template: 'challenge',
  },
  {
    id: 'chal-aanw-5',
    type: 'challenge',
    skill: 'Aanwezigheid',
    text: 'Ga deze week elke avond 5 minuten naast je kind zitten zonder iets te doen of te zeggen',
    subtitle: 'Gewoon er zijn. Kijk wat er vanzelf ontstaat.',
    template: 'challenge',
  },
  {
    id: 'chal-emot-4',
    type: 'challenge',
    skill: 'Emotiecoaching',
    text: 'Reageer deze week bij elke emotie van je kind eerst met "Ik zie je" of "Ik snap het"',
    subtitle: 'Validatie voor oplossing. Altijd.',
    template: 'challenge',
  },
  {
    id: 'chal-emot-5',
    type: 'challenge',
    skill: 'Emotiecoaching',
    text: 'Lees deze week elke avond een prentenboek voor en bespreek de gevoelens van de personages',
    subtitle: 'Fictie is een veilige oefengrond voor echte emoties.',
    template: 'challenge',
  },
  {
    id: 'chal-zelf-5',
    type: 'challenge',
    skill: 'Zelfregulatie',
    text: 'Drink deze week geen koffie na 14:00 en ga een half uur eerder naar bed',
    subtitle: 'Je geduld begint bij je slaapkwaliteit.',
    template: 'challenge',
  },
  {
    id: 'chal-gren-4',
    type: 'challenge',
    skill: 'Grenzen',
    text: 'Maak deze week samen met je kind een lijstje van drie huisregels waar jullie het over eens zijn',
    subtitle: 'Regels die je samen maakt, worden beter nageleefd.',
    template: 'challenge',
  },
  {
    id: 'chal-auto-4',
    type: 'challenge',
    skill: 'Autonomie',
    text: 'Laat je kind deze week zelf bepalen in welke volgorde het zijn huiswerk maakt',
    subtitle: 'Kleine keuzes bouwen aan groot zelfvertrouwen.',
    template: 'challenge',
  },
  {
    id: 'chal-auto-5',
    type: 'challenge',
    skill: 'Autonomie',
    text: 'Geef je kind deze week de leiding over een gezinsactiviteit in het weekend',
    subtitle: 'Wat, waar en hoe - laat het helemaal aan je kind.',
    template: 'challenge',
  },
  {
    id: 'chal-hers-4',
    type: 'challenge',
    skill: 'Herstel',
    text: 'Denk terug aan een recent moment waarop je te streng reageerde en bespreek het alsnog met je kind',
    subtitle: 'Het is nooit te laat om terug te komen op een moment.',
    template: 'challenge',
  },
  {
    id: 'chal-verb-5',
    type: 'challenge',
    skill: 'Verbinding',
    text: 'Leer deze week iets nieuws van je kind: een spel, een liedje, een trucje',
    subtitle: 'Laat je kind de leraar zijn. Het straalt als het jou iets kan bijbrengen.',
    template: 'challenge',
  },
  {
    id: 'chal-verb-6',
    type: 'challenge',
    skill: 'Verbinding',
    text: 'Maak deze week een foto samen en stuur het naar je kind met de tekst: "Fijn moment"',
    subtitle: 'Kleine gebaren houden de verbinding levend.',
    template: 'challenge',
  },
  {
    id: 'chal-refl-5',
    type: 'challenge',
    skill: 'Reflectie',
    text: 'Schrijf drie eigenschappen op die je als vader wilt meegeven aan je kind en reflecteer: leef je ze zelf voor?',
    subtitle: 'Kinderen doen wat je doet, niet wat je zegt.',
    template: 'challenge',
  },
  {
    id: 'chal-hers-5',
    type: 'challenge',
    skill: 'Herstel',
    text: 'Schrijf je kind een kort briefje na een lastig moment deze week',
    subtitle: 'Woorden op papier blijven langer hangen dan gesproken woorden.',
    template: 'challenge',
  },

  // ════════════════════════════════════════════════════════════════════
  // NEW COMPARISONS (12)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'comp-29',
    type: 'comparison',
    skill: 'Emotiecoaching',
    text: 'Daar is toch niks ergs aan?',
    subtitle: 'Ik merk dat dit belangrijk voor je is. Vertel eens.',
    template: 'comparison',
  },
  {
    id: 'comp-30',
    type: 'comparison',
    skill: 'Aanwezigheid',
    text: 'Ik heb nu geen tijd voor dit soort dingen.',
    subtitle: 'Ik heb nu even vijf minuten. Wat wil je me vertellen?',
    template: 'comparison',
  },
  {
    id: 'comp-31',
    type: 'comparison',
    skill: 'Grenzen',
    text: 'Oké, dan mag het deze keer wel.',
    subtitle: 'Ik weet dat het vervelend is. De afspraak blijft staan.',
    template: 'comparison',
  },
  {
    id: 'comp-32',
    type: 'comparison',
    skill: 'Autonomie',
    text: 'Nee, zo moet het niet. Geef maar hier.',
    subtitle: 'Ik zie dat het anders is dan ik zou doen. Hoe heb je dat bedacht?',
    template: 'comparison',
  },
  {
    id: 'comp-33',
    type: 'comparison',
    skill: 'Herstel',
    text: 'Ik was niet boos, ik was gewoon duidelijk.',
    subtitle: 'Ik merkte dat ik boos werd en dat was niet terecht. Sorry.',
    template: 'comparison',
  },
  {
    id: 'comp-34',
    type: 'comparison',
    skill: 'Zelfregulatie',
    text: 'Moet ik nou alles tien keer zeggen?!',
    subtitle: 'Ik merk dat ik mezelf begin te herhalen. Hoe kan ik je helpen om het te onthouden?',
    template: 'comparison',
  },
  {
    id: 'comp-35',
    type: 'comparison',
    skill: 'Verbinding',
    text: 'Dat snap je toch niet, je bent nog te jong.',
    subtitle: 'Zal ik het proberen uit te leggen op jouw manier?',
    template: 'comparison',
  },
  {
    id: 'comp-36',
    type: 'comparison',
    skill: 'Reflectie',
    text: 'Ik had het ook niet makkelijk vroeger.',
    subtitle: 'Ik herken dit gevoel uit mijn eigen jeugd. Ik wil het voor jou anders maken.',
    template: 'comparison',
  },
  {
    id: 'comp-37',
    type: 'comparison',
    skill: 'Aanwezigheid',
    text: 'Ja ja, heel mooi (zonder op te kijken).',
    subtitle: 'Wacht even, ik wil dit echt goed zien. Laat nog eens zien?',
    template: 'comparison',
  },
  {
    id: 'comp-38',
    type: 'comparison',
    skill: 'Emotiecoaching',
    text: 'Je overdrijft, het is maar een speelgoedje.',
    subtitle: 'Ik zie dat je hier verdrietig over bent. Het was belangrijk voor je.',
    template: 'comparison',
  },
  {
    id: 'comp-39',
    type: 'comparison',
    skill: 'Grenzen',
    text: 'Omdat het gewoon zo hoort!',
    subtitle: 'Deze regel is er zodat je veilig bent. Zal ik uitleggen waarom?',
    template: 'comparison',
  },
  {
    id: 'comp-40',
    type: 'comparison',
    skill: 'Zelfregulatie',
    text: 'Ik heb echt even genoeg van jullie!',
    subtitle: 'Ik heb even pauze nodig. Over tien minuten ben ik er weer voor jullie.',
    template: 'comparison',
  },

  // ════════════════════════════════════════════════════════════════════
  // NEW QUOTES (16)
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'quote-25',
    type: 'quote',
    skill: 'Aanwezigheid',
    text: 'De dagen zijn lang, maar de jaren zijn kort. Vandaag is nooit meer terug.',
    template: 'quote',
  },
  {
    id: 'quote-26',
    type: 'quote',
    skill: 'Emotiecoaching',
    text: 'Een kind dat mag voelen, wordt een volwassene die kan denken.',
    template: 'quote',
  },
  {
    id: 'quote-27',
    type: 'quote',
    skill: 'Zelfregulatie',
    text: 'Je hoeft geen heilige te zijn. Je hoeft alleen maar vaker te pauzeren dan te ontploffen.',
    template: 'quote',
  },
  {
    id: 'quote-28',
    type: 'quote',
    skill: 'Grenzen',
    text: 'De grenzen die je met liefde stelt, worden de fundamenten waarop je kind zijn leven bouwt.',
    template: 'quote',
  },
  {
    id: 'quote-29',
    type: 'quote',
    skill: 'Autonomie',
    text: 'Een kind dat nooit mag struikelen, leert nooit om op te staan.',
    template: 'quote',
  },
  {
    id: 'quote-30',
    type: 'quote',
    skill: 'Herstel',
    text: 'De vader die terugkomt na een fout, leert zijn kind meer dan de vader die nooit een fout maakt.',
    template: 'quote',
  },
  {
    id: 'quote-31',
    type: 'quote',
    skill: 'Verbinding',
    text: 'Verbinding vraagt geen grote gebaren. Het vraagt kleine momenten van echte aandacht, elke dag opnieuw.',
    template: 'quote',
  },
  {
    id: 'quote-32',
    type: 'quote',
    skill: 'Reflectie',
    text: 'Wie je bent als vader is belangrijker dan wat je doet als vader.',
    template: 'quote',
  },
  {
    id: 'quote-33',
    type: 'quote',
    skill: 'Aanwezigheid',
    text: 'Je kind vraagt niet om je tijd. Het vraagt om jou.',
    template: 'quote',
  },
  {
    id: 'quote-34',
    type: 'quote',
    skill: 'Emotiecoaching',
    text: 'Achter elk lastig gedrag zit een kind dat iets probeert te zeggen. Luister naar wat het niet kan uitspreken.',
    template: 'quote',
  },
  {
    id: 'quote-35',
    type: 'quote',
    skill: 'Zelfregulatie',
    text: 'Niet reageren is soms de krachtigste actie die een vader kan ondernemen.',
    template: 'quote',
  },
  {
    id: 'quote-36',
    type: 'quote',
    skill: 'Grenzen',
    text: 'Nee zeggen uit liefde is moeilijker dan ja zeggen uit gemak. Kies het moeilijke.',
    template: 'quote',
  },
  {
    id: 'quote-37',
    type: 'quote',
    skill: 'Verbinding',
    text: 'Het gaat er niet om hoeveel je voor je kind doet. Het gaat erom hoeveel je kind voelt dat je er bent.',
    template: 'quote',
  },
  {
    id: 'quote-38',
    type: 'quote',
    skill: 'Herstel',
    text: 'Een gebroken moment dat hersteld wordt, is sterker dan een moment dat nooit brak.',
    template: 'quote',
  },
  {
    id: 'quote-39',
    type: 'quote',
    skill: 'Reflectie',
    text: 'De vader die je had, bepaalt niet de vader die je bent. De vader die je wilt zijn - daar begint het mee.',
    template: 'quote',
  },
  {
    id: 'quote-40',
    type: 'quote',
    skill: 'Autonomie',
    text: 'Je taak is niet om het pad voor je kind vrij te maken. Je taak is om een kind te vormen dat elk pad aankan.',
    template: 'quote',
  },

  // ════════════════════════════════════════════════════════════════════
  // ANNOUNCEMENTS
  // ════════════════════════════════════════════════════════════════════
  {
    id: 'announce-app-testers',
    type: 'cta',
    skill: '',
    text: 'Wil jij De Vadercoach app als eerste testen?',
    subtitle: 'Word beta-tester',
    template: 'cta',
    caption: `We zoeken vaders die onze gloednieuwe app willen testen! De Vadercoach app geeft je elke week persoonlijke oefeningen, trainingen en inzichten om een betere vader te worden.

Wat we vragen:
- Installeer de app en probeer hem uit
- Geef eerlijke feedback via de app of DM

Hoe doe je mee?

iPhone: open de TestFlight-link in onze bio en je kunt direct aan de slag.

Android: stuur ons een DM met je Gmail-adres, dan voegen we je toe als tester.

De eerste testers krijgen voor altijd gratis toegang. Doe je mee?

#vaderschap #opvoeden #devadercoach #app #beta #testen`,
  },
];

// ════════════════════════════════════════════════════════════════════
// Helper functions
// ════════════════════════════════════════════════════════════════════

export function getRandomContent(type?: SocialContent['type'], skill?: string): SocialContent {
  let filtered = SOCIAL_CONTENT;
  if (type) {
    filtered = filtered.filter((c) => c.type === type);
  }
  if (skill) {
    filtered = filtered.filter((c) => c.skill === skill);
  }
  if (filtered.length === 0) {
    // Fallback to unfiltered if no match
    filtered = SOCIAL_CONTENT;
  }
  return filtered[Math.floor(Math.random() * filtered.length)];
}

export function getContentByType(type: SocialContent['type']): SocialContent[] {
  return SOCIAL_CONTENT.filter((c) => c.type === type);
}

export function getContentBySkill(skill: string): SocialContent[] {
  return SOCIAL_CONTENT.filter((c) => c.skill === skill);
}
